# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ghmmwrapper', [dirname(__file__)])
        except ImportError:
            import _ghmmwrapper
            return _ghmmwrapper
        if fp is not None:
            try:
                _mod = imp.load_module('_ghmmwrapper', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ghmmwrapper = swig_import_helper()
    del swig_import_helper
else:
    import _ghmmwrapper
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def cp_class_change(*args):
  return _ghmmwrapper.cp_class_change(*args)
cp_class_change = _ghmmwrapper.cp_class_change

def setSwitchingFunction(*args):
  return _ghmmwrapper.setSwitchingFunction(*args)
setSwitchingFunction = _ghmmwrapper.setSwitchingFunction

def python_class_change(*args):
  return _ghmmwrapper.python_class_change(*args)
python_class_change = _ghmmwrapper.python_class_change

def setPythonSwitching(*args):
  return _ghmmwrapper.setPythonSwitching(*args)
setPythonSwitching = _ghmmwrapper.setPythonSwitching
class threshold_user_data(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, threshold_user_data, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, threshold_user_data, name)
    __repr__ = _swig_repr
    __swig_setmethods__["seq_index"] = _ghmmwrapper.threshold_user_data_seq_index_set
    __swig_getmethods__["seq_index"] = _ghmmwrapper.threshold_user_data_seq_index_get
    if _newclass:seq_index = _swig_property(_ghmmwrapper.threshold_user_data_seq_index_get, _ghmmwrapper.threshold_user_data_seq_index_set)
    __swig_setmethods__["threshold"] = _ghmmwrapper.threshold_user_data_threshold_set
    __swig_getmethods__["threshold"] = _ghmmwrapper.threshold_user_data_threshold_get
    if _newclass:threshold = _swig_property(_ghmmwrapper.threshold_user_data_threshold_get, _ghmmwrapper.threshold_user_data_threshold_set)
    __swig_setmethods__["offset_x"] = _ghmmwrapper.threshold_user_data_offset_x_set
    __swig_getmethods__["offset_x"] = _ghmmwrapper.threshold_user_data_offset_x_get
    if _newclass:offset_x = _swig_property(_ghmmwrapper.threshold_user_data_offset_x_get, _ghmmwrapper.threshold_user_data_offset_x_set)
    __swig_setmethods__["offset_y"] = _ghmmwrapper.threshold_user_data_offset_y_set
    __swig_getmethods__["offset_y"] = _ghmmwrapper.threshold_user_data_offset_y_get
    if _newclass:offset_y = _swig_property(_ghmmwrapper.threshold_user_data_offset_y_get, _ghmmwrapper.threshold_user_data_offset_y_set)
    def __init__(self): 
        this = _ghmmwrapper.new_threshold_user_data()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_threshold_user_data
    __del__ = lambda self : None;
threshold_user_data_swigregister = _ghmmwrapper.threshold_user_data_swigregister
threshold_user_data_swigregister(threshold_user_data)

class boolean_user_data(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, boolean_user_data, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, boolean_user_data, name)
    __repr__ = _swig_repr
    __swig_setmethods__["seq_index"] = _ghmmwrapper.boolean_user_data_seq_index_set
    __swig_getmethods__["seq_index"] = _ghmmwrapper.boolean_user_data_seq_index_get
    if _newclass:seq_index = _swig_property(_ghmmwrapper.boolean_user_data_seq_index_get, _ghmmwrapper.boolean_user_data_seq_index_set)
    __swig_setmethods__["offset_x"] = _ghmmwrapper.boolean_user_data_offset_x_set
    __swig_getmethods__["offset_x"] = _ghmmwrapper.boolean_user_data_offset_x_get
    if _newclass:offset_x = _swig_property(_ghmmwrapper.boolean_user_data_offset_x_get, _ghmmwrapper.boolean_user_data_offset_x_set)
    __swig_setmethods__["offset_y"] = _ghmmwrapper.boolean_user_data_offset_y_set
    __swig_getmethods__["offset_y"] = _ghmmwrapper.boolean_user_data_offset_y_get
    if _newclass:offset_y = _swig_property(_ghmmwrapper.boolean_user_data_offset_y_get, _ghmmwrapper.boolean_user_data_offset_y_set)
    def __init__(self): 
        this = _ghmmwrapper.new_boolean_user_data()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_boolean_user_data
    __del__ = lambda self : None;
boolean_user_data_swigregister = _ghmmwrapper.boolean_user_data_swigregister
boolean_user_data_swigregister(boolean_user_data)


def gt_sum(*args):
  return _ghmmwrapper.gt_sum(*args)
gt_sum = _ghmmwrapper.gt_sum

def lt_sum(*args):
  return _ghmmwrapper.lt_sum(*args)
lt_sum = _ghmmwrapper.lt_sum

def boolean_and(*args):
  return _ghmmwrapper.boolean_and(*args)
boolean_and = _ghmmwrapper.boolean_and

def boolean_or(*args):
  return _ghmmwrapper.boolean_or(*args)
boolean_or = _ghmmwrapper.boolean_or

def set_to_lt_sum(*args):
  return _ghmmwrapper.set_to_lt_sum(*args)
set_to_lt_sum = _ghmmwrapper.set_to_lt_sum

def set_to_gt_sum(*args):
  return _ghmmwrapper.set_to_gt_sum(*args)
set_to_gt_sum = _ghmmwrapper.set_to_gt_sum

def set_to_boolean_and(*args):
  return _ghmmwrapper.set_to_boolean_and(*args)
set_to_boolean_and = _ghmmwrapper.set_to_boolean_and

def set_to_boolean_or(*args):
  return _ghmmwrapper.set_to_boolean_or(*args)
set_to_boolean_or = _ghmmwrapper.set_to_boolean_or
SMO_FILE_SUPPORT = _ghmmwrapper.SMO_FILE_SUPPORT
ASCI_SEQ_FILE = _ghmmwrapper.ASCI_SEQ_FILE
SEQ_LABEL_FIELD = _ghmmwrapper.SEQ_LABEL_FIELD
kNotSpecified = _ghmmwrapper.kNotSpecified
kLeftRight = _ghmmwrapper.kLeftRight
kSilentStates = _ghmmwrapper.kSilentStates
kTiedEmissions = _ghmmwrapper.kTiedEmissions
kUntied = _ghmmwrapper.kUntied
kHigherOrderEmissions = _ghmmwrapper.kHigherOrderEmissions
kBackgroundDistributions = _ghmmwrapper.kBackgroundDistributions
kNoBackgroundDistribution = _ghmmwrapper.kNoBackgroundDistribution
kLabeledStates = _ghmmwrapper.kLabeledStates
kTransitionClasses = _ghmmwrapper.kTransitionClasses
kDiscreteHMM = _ghmmwrapper.kDiscreteHMM
kContinuousHMM = _ghmmwrapper.kContinuousHMM
kPairHMM = _ghmmwrapper.kPairHMM
kMultivariate = _ghmmwrapper.kMultivariate
EPS_ITER_BW = _ghmmwrapper.EPS_ITER_BW
MAX_ITER_BW = _ghmmwrapper.MAX_ITER_BW

def set_pylogging(*args):
  return _ghmmwrapper.set_pylogging(*args)
set_pylogging = _ghmmwrapper.set_pylogging

def ghmm_rng_init():
  return _ghmmwrapper.ghmm_rng_init()
ghmm_rng_init = _ghmmwrapper.ghmm_rng_init

def ghmm_rng_timeseed(*args):
  return _ghmmwrapper.ghmm_rng_timeseed(*args)
ghmm_rng_timeseed = _ghmmwrapper.ghmm_rng_timeseed

def time_seed():
  return _ghmmwrapper.time_seed()
time_seed = _ghmmwrapper.time_seed

def ighmm_rand_normal_density_trunc(*args):
  return _ghmmwrapper.ighmm_rand_normal_density_trunc(*args)
ighmm_rand_normal_density_trunc = _ghmmwrapper.ighmm_rand_normal_density_trunc
class ghmm_alphabet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_alphabet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_alphabet, name)
    __repr__ = _swig_repr
    __swig_setmethods__["id"] = _ghmmwrapper.ghmm_alphabet_id_set
    __swig_getmethods__["id"] = _ghmmwrapper.ghmm_alphabet_id_get
    if _newclass:id = _swig_property(_ghmmwrapper.ghmm_alphabet_id_get, _ghmmwrapper.ghmm_alphabet_id_set)
    __swig_setmethods__["description"] = _ghmmwrapper.ghmm_alphabet_description_set
    __swig_getmethods__["description"] = _ghmmwrapper.ghmm_alphabet_description_get
    if _newclass:description = _swig_property(_ghmmwrapper.ghmm_alphabet_description_get, _ghmmwrapper.ghmm_alphabet_description_set)
    __swig_setmethods__["size"] = _ghmmwrapper.ghmm_alphabet_size_set
    __swig_getmethods__["size"] = _ghmmwrapper.ghmm_alphabet_size_get
    if _newclass:size = _swig_property(_ghmmwrapper.ghmm_alphabet_size_get, _ghmmwrapper.ghmm_alphabet_size_set)
    __swig_setmethods__["symbols"] = _ghmmwrapper.ghmm_alphabet_symbols_set
    __swig_getmethods__["symbols"] = _ghmmwrapper.ghmm_alphabet_symbols_get
    if _newclass:symbols = _swig_property(_ghmmwrapper.ghmm_alphabet_symbols_get, _ghmmwrapper.ghmm_alphabet_symbols_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_alphabet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_alphabet
    __del__ = lambda self : None;
    def getSymbol(self, *args): return _ghmmwrapper.ghmm_alphabet_getSymbol(self, *args)
    def setSymbol(self, *args): return _ghmmwrapper.ghmm_alphabet_setSymbol(self, *args)
ghmm_alphabet_swigregister = _ghmmwrapper.ghmm_alphabet_swigregister
ghmm_alphabet_swigregister(ghmm_alphabet)

class ghmm_cseq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_cseq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_cseq, name)
    __repr__ = _swig_repr
    __swig_setmethods__["seq"] = _ghmmwrapper.ghmm_cseq_seq_set
    __swig_getmethods__["seq"] = _ghmmwrapper.ghmm_cseq_seq_get
    if _newclass:seq = _swig_property(_ghmmwrapper.ghmm_cseq_seq_get, _ghmmwrapper.ghmm_cseq_seq_set)
    __swig_setmethods__["seq_len"] = _ghmmwrapper.ghmm_cseq_seq_len_set
    __swig_getmethods__["seq_len"] = _ghmmwrapper.ghmm_cseq_seq_len_get
    if _newclass:seq_len = _swig_property(_ghmmwrapper.ghmm_cseq_seq_len_get, _ghmmwrapper.ghmm_cseq_seq_len_set)
    __swig_setmethods__["seq_id"] = _ghmmwrapper.ghmm_cseq_seq_id_set
    __swig_getmethods__["seq_id"] = _ghmmwrapper.ghmm_cseq_seq_id_get
    if _newclass:seq_id = _swig_property(_ghmmwrapper.ghmm_cseq_seq_id_get, _ghmmwrapper.ghmm_cseq_seq_id_set)
    __swig_setmethods__["seq_w"] = _ghmmwrapper.ghmm_cseq_seq_w_set
    __swig_getmethods__["seq_w"] = _ghmmwrapper.ghmm_cseq_seq_w_get
    if _newclass:seq_w = _swig_property(_ghmmwrapper.ghmm_cseq_seq_w_get, _ghmmwrapper.ghmm_cseq_seq_w_set)
    __swig_setmethods__["seq_number"] = _ghmmwrapper.ghmm_cseq_seq_number_set
    __swig_getmethods__["seq_number"] = _ghmmwrapper.ghmm_cseq_seq_number_get
    if _newclass:seq_number = _swig_property(_ghmmwrapper.ghmm_cseq_seq_number_get, _ghmmwrapper.ghmm_cseq_seq_number_set)
    __swig_setmethods__["capacity"] = _ghmmwrapper.ghmm_cseq_capacity_set
    __swig_getmethods__["capacity"] = _ghmmwrapper.ghmm_cseq_capacity_get
    if _newclass:capacity = _swig_property(_ghmmwrapper.ghmm_cseq_capacity_get, _ghmmwrapper.ghmm_cseq_capacity_set)
    __swig_setmethods__["total_w"] = _ghmmwrapper.ghmm_cseq_total_w_set
    __swig_getmethods__["total_w"] = _ghmmwrapper.ghmm_cseq_total_w_get
    if _newclass:total_w = _swig_property(_ghmmwrapper.ghmm_cseq_total_w_get, _ghmmwrapper.ghmm_cseq_total_w_set)
    __swig_setmethods__["dim"] = _ghmmwrapper.ghmm_cseq_dim_set
    __swig_getmethods__["dim"] = _ghmmwrapper.ghmm_cseq_dim_get
    if _newclass:dim = _swig_property(_ghmmwrapper.ghmm_cseq_dim_get, _ghmmwrapper.ghmm_cseq_dim_set)
    __swig_setmethods__["flags"] = _ghmmwrapper.ghmm_cseq_flags_set
    __swig_getmethods__["flags"] = _ghmmwrapper.ghmm_cseq_flags_get
    if _newclass:flags = _swig_property(_ghmmwrapper.ghmm_cseq_flags_get, _ghmmwrapper.ghmm_cseq_flags_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_cseq(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_cseq
    __del__ = lambda self : None;
    def get_singlesequence(self, *args): return _ghmmwrapper.ghmm_cseq_get_singlesequence(self, *args)
    def subseq_free(self): return _ghmmwrapper.ghmm_cseq_subseq_free(self)
    def add(self, *args): return _ghmmwrapper.ghmm_cseq_add(self, *args)
    def clean(self): return _ghmmwrapper.ghmm_cseq_clean(self)
    def partition(self, *args): return _ghmmwrapper.ghmm_cseq_partition(self, *args)
    def copy_all(self, *args): return _ghmmwrapper.ghmm_cseq_copy_all(self, *args)
    def getSequence(self, *args): return _ghmmwrapper.ghmm_cseq_getSequence(self, *args)
    def setSequence(self, *args): return _ghmmwrapper.ghmm_cseq_setSequence(self, *args)
    def getSymbol(self, *args): return _ghmmwrapper.ghmm_cseq_getSymbol(self, *args)
    def setSymbol(self, *args): return _ghmmwrapper.ghmm_cseq_setSymbol(self, *args)
    def getLength(self, *args): return _ghmmwrapper.ghmm_cseq_getLength(self, *args)
    def setLength(self, *args): return _ghmmwrapper.ghmm_cseq_setLength(self, *args)
    def getWeight(self, *args): return _ghmmwrapper.ghmm_cseq_getWeight(self, *args)
    def setWeight(self, *args): return _ghmmwrapper.ghmm_cseq_setWeight(self, *args)
    def write(self, *args): return _ghmmwrapper.ghmm_cseq_write(self, *args)
ghmm_cseq_swigregister = _ghmmwrapper.ghmm_cseq_swigregister
ghmm_cseq_swigregister(ghmm_cseq)


def ghmm_cseq_free(*args):
  return _ghmmwrapper.ghmm_cseq_free(*args)
ghmm_cseq_free = _ghmmwrapper.ghmm_cseq_free

def ghmm_cseq_calloc(*args):
  return _ghmmwrapper.ghmm_cseq_calloc(*args)
ghmm_cseq_calloc = _ghmmwrapper.ghmm_cseq_calloc

def cseq_ptr_array_alloc(*args):
  return _ghmmwrapper.cseq_ptr_array_alloc(*args)
cseq_ptr_array_alloc = _ghmmwrapper.cseq_ptr_array_alloc

def cseq_ptr_array_getitem(*args):
  return _ghmmwrapper.cseq_ptr_array_getitem(*args)
cseq_ptr_array_getitem = _ghmmwrapper.cseq_ptr_array_getitem

def cseq_ptr_array_setitem(*args):
  return _ghmmwrapper.cseq_ptr_array_setitem(*args)
cseq_ptr_array_setitem = _ghmmwrapper.cseq_ptr_array_setitem
class ghmm_dseq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dseq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dseq, name)
    __repr__ = _swig_repr
    __swig_setmethods__["seq"] = _ghmmwrapper.ghmm_dseq_seq_set
    __swig_getmethods__["seq"] = _ghmmwrapper.ghmm_dseq_seq_get
    if _newclass:seq = _swig_property(_ghmmwrapper.ghmm_dseq_seq_get, _ghmmwrapper.ghmm_dseq_seq_set)
    __swig_setmethods__["states"] = _ghmmwrapper.ghmm_dseq_states_set
    __swig_getmethods__["states"] = _ghmmwrapper.ghmm_dseq_states_get
    if _newclass:states = _swig_property(_ghmmwrapper.ghmm_dseq_states_get, _ghmmwrapper.ghmm_dseq_states_set)
    __swig_setmethods__["seq_len"] = _ghmmwrapper.ghmm_dseq_seq_len_set
    __swig_getmethods__["seq_len"] = _ghmmwrapper.ghmm_dseq_seq_len_get
    if _newclass:seq_len = _swig_property(_ghmmwrapper.ghmm_dseq_seq_len_get, _ghmmwrapper.ghmm_dseq_seq_len_set)
    __swig_setmethods__["states_len"] = _ghmmwrapper.ghmm_dseq_states_len_set
    __swig_getmethods__["states_len"] = _ghmmwrapper.ghmm_dseq_states_len_get
    if _newclass:states_len = _swig_property(_ghmmwrapper.ghmm_dseq_states_len_get, _ghmmwrapper.ghmm_dseq_states_len_set)
    __swig_setmethods__["seq_id"] = _ghmmwrapper.ghmm_dseq_seq_id_set
    __swig_getmethods__["seq_id"] = _ghmmwrapper.ghmm_dseq_seq_id_get
    if _newclass:seq_id = _swig_property(_ghmmwrapper.ghmm_dseq_seq_id_get, _ghmmwrapper.ghmm_dseq_seq_id_set)
    __swig_setmethods__["seq_w"] = _ghmmwrapper.ghmm_dseq_seq_w_set
    __swig_getmethods__["seq_w"] = _ghmmwrapper.ghmm_dseq_seq_w_get
    if _newclass:seq_w = _swig_property(_ghmmwrapper.ghmm_dseq_seq_w_get, _ghmmwrapper.ghmm_dseq_seq_w_set)
    __swig_setmethods__["seq_number"] = _ghmmwrapper.ghmm_dseq_seq_number_set
    __swig_getmethods__["seq_number"] = _ghmmwrapper.ghmm_dseq_seq_number_get
    if _newclass:seq_number = _swig_property(_ghmmwrapper.ghmm_dseq_seq_number_get, _ghmmwrapper.ghmm_dseq_seq_number_set)
    __swig_setmethods__["capacity"] = _ghmmwrapper.ghmm_dseq_capacity_set
    __swig_getmethods__["capacity"] = _ghmmwrapper.ghmm_dseq_capacity_get
    if _newclass:capacity = _swig_property(_ghmmwrapper.ghmm_dseq_capacity_get, _ghmmwrapper.ghmm_dseq_capacity_set)
    __swig_setmethods__["total_w"] = _ghmmwrapper.ghmm_dseq_total_w_set
    __swig_getmethods__["total_w"] = _ghmmwrapper.ghmm_dseq_total_w_get
    if _newclass:total_w = _swig_property(_ghmmwrapper.ghmm_dseq_total_w_get, _ghmmwrapper.ghmm_dseq_total_w_set)
    __swig_setmethods__["state_labels"] = _ghmmwrapper.ghmm_dseq_state_labels_set
    __swig_getmethods__["state_labels"] = _ghmmwrapper.ghmm_dseq_state_labels_get
    if _newclass:state_labels = _swig_property(_ghmmwrapper.ghmm_dseq_state_labels_get, _ghmmwrapper.ghmm_dseq_state_labels_set)
    __swig_setmethods__["state_labels_len"] = _ghmmwrapper.ghmm_dseq_state_labels_len_set
    __swig_getmethods__["state_labels_len"] = _ghmmwrapper.ghmm_dseq_state_labels_len_get
    if _newclass:state_labels_len = _swig_property(_ghmmwrapper.ghmm_dseq_state_labels_len_get, _ghmmwrapper.ghmm_dseq_state_labels_len_set)
    __swig_setmethods__["flags"] = _ghmmwrapper.ghmm_dseq_flags_set
    __swig_getmethods__["flags"] = _ghmmwrapper.ghmm_dseq_flags_get
    if _newclass:flags = _swig_property(_ghmmwrapper.ghmm_dseq_flags_get, _ghmmwrapper.ghmm_dseq_flags_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_dseq(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dseq
    __del__ = lambda self : None;
    def init_labels(self, *args): return _ghmmwrapper.ghmm_dseq_init_labels(self, *args)
    def calloc_state_labels(self): return _ghmmwrapper.ghmm_dseq_calloc_state_labels(self)
    def get_singlesequence(self, *args): return _ghmmwrapper.ghmm_dseq_get_singlesequence(self, *args)
    def subseq_free(self): return _ghmmwrapper.ghmm_dseq_subseq_free(self)
    def max_symbol(self): return _ghmmwrapper.ghmm_dseq_max_symbol(self)
    def add(self, *args): return _ghmmwrapper.ghmm_dseq_add(self, *args)
    def check(self, *args): return _ghmmwrapper.ghmm_dseq_check(self, *args)
    def clean(self): return _ghmmwrapper.ghmm_dseq_clean(self)
    def getSequence(self, *args): return _ghmmwrapper.ghmm_dseq_getSequence(self, *args)
    def setSequence(self, *args): return _ghmmwrapper.ghmm_dseq_setSequence(self, *args)
    def getSymbol(self, *args): return _ghmmwrapper.ghmm_dseq_getSymbol(self, *args)
    def setSymbol(self, *args): return _ghmmwrapper.ghmm_dseq_setSymbol(self, *args)
    def getLength(self, *args): return _ghmmwrapper.ghmm_dseq_getLength(self, *args)
    def setLength(self, *args): return _ghmmwrapper.ghmm_dseq_setLength(self, *args)
    def getWeight(self, *args): return _ghmmwrapper.ghmm_dseq_getWeight(self, *args)
    def setWeight(self, *args): return _ghmmwrapper.ghmm_dseq_setWeight(self, *args)
    def getLabels(self, *args): return _ghmmwrapper.ghmm_dseq_getLabels(self, *args)
    def setLabels(self, *args): return _ghmmwrapper.ghmm_dseq_setLabels(self, *args)
    def getLabelsLength(self, *args): return _ghmmwrapper.ghmm_dseq_getLabelsLength(self, *args)
    def setLabelsLength(self, *args): return _ghmmwrapper.ghmm_dseq_setLabelsLength(self, *args)
    def copyStateLabel(self, *args): return _ghmmwrapper.ghmm_dseq_copyStateLabel(self, *args)
    def write(self, *args): return _ghmmwrapper.ghmm_dseq_write(self, *args)
ghmm_dseq_swigregister = _ghmmwrapper.ghmm_dseq_swigregister
ghmm_dseq_swigregister(ghmm_dseq)


def ghmm_dseq_free(*args):
  return _ghmmwrapper.ghmm_dseq_free(*args)
ghmm_dseq_free = _ghmmwrapper.ghmm_dseq_free

def ghmm_dseq_calloc(*args):
  return _ghmmwrapper.ghmm_dseq_calloc(*args)
ghmm_dseq_calloc = _ghmmwrapper.ghmm_dseq_calloc

def dseq_ptr_array_alloc(*args):
  return _ghmmwrapper.dseq_ptr_array_alloc(*args)
dseq_ptr_array_alloc = _ghmmwrapper.dseq_ptr_array_alloc

def dseq_ptr_array_getitem(*args):
  return _ghmmwrapper.dseq_ptr_array_getitem(*args)
dseq_ptr_array_getitem = _ghmmwrapper.dseq_ptr_array_getitem

def dseq_ptr_array_setitem(*args):
  return _ghmmwrapper.dseq_ptr_array_setitem(*args)
dseq_ptr_array_setitem = _ghmmwrapper.dseq_ptr_array_setitem
class ghmm_dpseq(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dpseq, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dpseq, name)
    __repr__ = _swig_repr
    __swig_setmethods__["seq"] = _ghmmwrapper.ghmm_dpseq_seq_set
    __swig_getmethods__["seq"] = _ghmmwrapper.ghmm_dpseq_seq_get
    if _newclass:seq = _swig_property(_ghmmwrapper.ghmm_dpseq_seq_get, _ghmmwrapper.ghmm_dpseq_seq_set)
    __swig_setmethods__["number_of_alphabets"] = _ghmmwrapper.ghmm_dpseq_number_of_alphabets_set
    __swig_getmethods__["number_of_alphabets"] = _ghmmwrapper.ghmm_dpseq_number_of_alphabets_get
    if _newclass:number_of_alphabets = _swig_property(_ghmmwrapper.ghmm_dpseq_number_of_alphabets_get, _ghmmwrapper.ghmm_dpseq_number_of_alphabets_set)
    __swig_setmethods__["d_value"] = _ghmmwrapper.ghmm_dpseq_d_value_set
    __swig_getmethods__["d_value"] = _ghmmwrapper.ghmm_dpseq_d_value_get
    if _newclass:d_value = _swig_property(_ghmmwrapper.ghmm_dpseq_d_value_get, _ghmmwrapper.ghmm_dpseq_d_value_set)
    __swig_setmethods__["number_of_d_seqs"] = _ghmmwrapper.ghmm_dpseq_number_of_d_seqs_set
    __swig_getmethods__["number_of_d_seqs"] = _ghmmwrapper.ghmm_dpseq_number_of_d_seqs_get
    if _newclass:number_of_d_seqs = _swig_property(_ghmmwrapper.ghmm_dpseq_number_of_d_seqs_get, _ghmmwrapper.ghmm_dpseq_number_of_d_seqs_set)
    __swig_setmethods__["length"] = _ghmmwrapper.ghmm_dpseq_length_set
    __swig_getmethods__["length"] = _ghmmwrapper.ghmm_dpseq_length_get
    if _newclass:length = _swig_property(_ghmmwrapper.ghmm_dpseq_length_get, _ghmmwrapper.ghmm_dpseq_length_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_dpseq(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dpseq
    __del__ = lambda self : None;
    def set_discrete(self, *args): return _ghmmwrapper.ghmm_dpseq_set_discrete(self, *args)
    def set_continuous(self, *args): return _ghmmwrapper.ghmm_dpseq_set_continuous(self, *args)
    def get_discrete(self, *args): return _ghmmwrapper.ghmm_dpseq_get_discrete(self, *args)
    def get_continuous(self, *args): return _ghmmwrapper.ghmm_dpseq_get_continuous(self, *args)
    def slice(self, *args): return _ghmmwrapper.ghmm_dpseq_slice(self, *args)
    def get_char(self, *args): return _ghmmwrapper.ghmm_dpseq_get_char(self, *args)
    def get_double(self, *args): return _ghmmwrapper.ghmm_dpseq_get_double(self, *args)
ghmm_dpseq_swigregister = _ghmmwrapper.ghmm_dpseq_swigregister
ghmm_dpseq_swigregister(ghmm_dpseq)


def ghmm_dpseq_free(*args):
  return _ghmmwrapper.ghmm_dpseq_free(*args)
ghmm_dpseq_free = _ghmmwrapper.ghmm_dpseq_free
normal = _ghmmwrapper.normal
normal_right = _ghmmwrapper.normal_right
normal_approx = _ghmmwrapper.normal_approx
normal_left = _ghmmwrapper.normal_left
uniform = _ghmmwrapper.uniform
binormal = _ghmmwrapper.binormal
multinormal = _ghmmwrapper.multinormal
density_number = _ghmmwrapper.density_number

def density_array_alloc(*args):
  return _ghmmwrapper.density_array_alloc(*args)
density_array_alloc = _ghmmwrapper.density_array_alloc

def density_array_getitem(*args):
  return _ghmmwrapper.density_array_getitem(*args)
density_array_getitem = _ghmmwrapper.density_array_getitem

def density_array_setitem(*args):
  return _ghmmwrapper.density_array_setitem(*args)
density_array_setitem = _ghmmwrapper.density_array_setitem
class ghmm_c_emission(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_c_emission, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_c_emission, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _ghmmwrapper.ghmm_c_emission_type_set
    __swig_getmethods__["type"] = _ghmmwrapper.ghmm_c_emission_type_get
    if _newclass:type = _swig_property(_ghmmwrapper.ghmm_c_emission_type_get, _ghmmwrapper.ghmm_c_emission_type_set)
    __swig_setmethods__["dimension"] = _ghmmwrapper.ghmm_c_emission_dimension_set
    __swig_getmethods__["dimension"] = _ghmmwrapper.ghmm_c_emission_dimension_get
    if _newclass:dimension = _swig_property(_ghmmwrapper.ghmm_c_emission_dimension_get, _ghmmwrapper.ghmm_c_emission_dimension_set)
    __swig_getmethods__["mean"] = _ghmmwrapper.ghmm_c_emission_mean_get
    if _newclass:mean = _swig_property(_ghmmwrapper.ghmm_c_emission_mean_get)
    __swig_getmethods__["variance"] = _ghmmwrapper.ghmm_c_emission_variance_get
    if _newclass:variance = _swig_property(_ghmmwrapper.ghmm_c_emission_variance_get)
    __swig_setmethods__["sigmainv"] = _ghmmwrapper.ghmm_c_emission_sigmainv_set
    __swig_getmethods__["sigmainv"] = _ghmmwrapper.ghmm_c_emission_sigmainv_get
    if _newclass:sigmainv = _swig_property(_ghmmwrapper.ghmm_c_emission_sigmainv_get, _ghmmwrapper.ghmm_c_emission_sigmainv_set)
    __swig_setmethods__["det"] = _ghmmwrapper.ghmm_c_emission_det_set
    __swig_getmethods__["det"] = _ghmmwrapper.ghmm_c_emission_det_get
    if _newclass:det = _swig_property(_ghmmwrapper.ghmm_c_emission_det_get, _ghmmwrapper.ghmm_c_emission_det_set)
    __swig_setmethods__["sigmacd"] = _ghmmwrapper.ghmm_c_emission_sigmacd_set
    __swig_getmethods__["sigmacd"] = _ghmmwrapper.ghmm_c_emission_sigmacd_get
    if _newclass:sigmacd = _swig_property(_ghmmwrapper.ghmm_c_emission_sigmacd_get, _ghmmwrapper.ghmm_c_emission_sigmacd_set)
    __swig_setmethods__["min"] = _ghmmwrapper.ghmm_c_emission_min_set
    __swig_getmethods__["min"] = _ghmmwrapper.ghmm_c_emission_min_get
    if _newclass:min = _swig_property(_ghmmwrapper.ghmm_c_emission_min_get, _ghmmwrapper.ghmm_c_emission_min_set)
    __swig_setmethods__["max"] = _ghmmwrapper.ghmm_c_emission_max_set
    __swig_getmethods__["max"] = _ghmmwrapper.ghmm_c_emission_max_get
    if _newclass:max = _swig_property(_ghmmwrapper.ghmm_c_emission_max_get, _ghmmwrapper.ghmm_c_emission_max_set)
    __swig_setmethods__["fixed"] = _ghmmwrapper.ghmm_c_emission_fixed_set
    __swig_getmethods__["fixed"] = _ghmmwrapper.ghmm_c_emission_fixed_get
    if _newclass:fixed = _swig_property(_ghmmwrapper.ghmm_c_emission_fixed_get, _ghmmwrapper.ghmm_c_emission_fixed_set)
    def setDensity(self, *args): return _ghmmwrapper.ghmm_c_emission_setDensity(self, *args)
    def getDensity(self): return _ghmmwrapper.ghmm_c_emission_getDensity(self)
    def getMeanVec(self): return _ghmmwrapper.ghmm_c_emission_getMeanVec(self)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_c_emission()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_c_emission
    __del__ = lambda self : None;
ghmm_c_emission_swigregister = _ghmmwrapper.ghmm_c_emission_swigregister
ghmm_c_emission_swigregister(ghmm_c_emission)

class ghmm_c_emission_variance(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_c_emission_variance, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_c_emission_variance, name)
    __repr__ = _swig_repr
    __swig_setmethods__["val"] = _ghmmwrapper.ghmm_c_emission_variance_val_set
    __swig_getmethods__["val"] = _ghmmwrapper.ghmm_c_emission_variance_val_get
    if _newclass:val = _swig_property(_ghmmwrapper.ghmm_c_emission_variance_val_get, _ghmmwrapper.ghmm_c_emission_variance_val_set)
    __swig_setmethods__["mat"] = _ghmmwrapper.ghmm_c_emission_variance_mat_set
    __swig_getmethods__["mat"] = _ghmmwrapper.ghmm_c_emission_variance_mat_get
    if _newclass:mat = _swig_property(_ghmmwrapper.ghmm_c_emission_variance_mat_get, _ghmmwrapper.ghmm_c_emission_variance_mat_set)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_c_emission_variance()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_c_emission_variance
    __del__ = lambda self : None;
ghmm_c_emission_variance_swigregister = _ghmmwrapper.ghmm_c_emission_variance_swigregister
ghmm_c_emission_variance_swigregister(ghmm_c_emission_variance)

class ghmm_c_emission_mean(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_c_emission_mean, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_c_emission_mean, name)
    __repr__ = _swig_repr
    __swig_setmethods__["val"] = _ghmmwrapper.ghmm_c_emission_mean_val_set
    __swig_getmethods__["val"] = _ghmmwrapper.ghmm_c_emission_mean_val_get
    if _newclass:val = _swig_property(_ghmmwrapper.ghmm_c_emission_mean_val_get, _ghmmwrapper.ghmm_c_emission_mean_val_set)
    __swig_setmethods__["vec"] = _ghmmwrapper.ghmm_c_emission_mean_vec_set
    __swig_getmethods__["vec"] = _ghmmwrapper.ghmm_c_emission_mean_vec_get
    if _newclass:vec = _swig_property(_ghmmwrapper.ghmm_c_emission_mean_vec_get, _ghmmwrapper.ghmm_c_emission_mean_vec_set)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_c_emission_mean()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_c_emission_mean
    __del__ = lambda self : None;
ghmm_c_emission_mean_swigregister = _ghmmwrapper.ghmm_c_emission_mean_swigregister
ghmm_c_emission_mean_swigregister(ghmm_c_emission_mean)


def c_emission_array_alloc(*args):
  return _ghmmwrapper.c_emission_array_alloc(*args)
c_emission_array_alloc = _ghmmwrapper.c_emission_array_alloc

def c_emission_array_getRef(*args):
  return _ghmmwrapper.c_emission_array_getRef(*args)
c_emission_array_getRef = _ghmmwrapper.c_emission_array_getRef

def c_emission_ptr_array_alloc(*args):
  return _ghmmwrapper.c_emission_ptr_array_alloc(*args)
c_emission_ptr_array_alloc = _ghmmwrapper.c_emission_ptr_array_alloc

def c_emission_ptr_array_getitem(*args):
  return _ghmmwrapper.c_emission_ptr_array_getitem(*args)
c_emission_ptr_array_getitem = _ghmmwrapper.c_emission_ptr_array_getitem

def c_emission_ptr_array_setitem(*args):
  return _ghmmwrapper.c_emission_ptr_array_setitem(*args)
c_emission_ptr_array_setitem = _ghmmwrapper.c_emission_ptr_array_setitem

def ighmm_invert_det(*args):
  return _ghmmwrapper.ighmm_invert_det(*args)
ighmm_invert_det = _ghmmwrapper.ighmm_invert_det
class ghmm_cstate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_cstate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_cstate, name)
    __repr__ = _swig_repr
    __swig_setmethods__["M"] = _ghmmwrapper.ghmm_cstate_M_set
    __swig_getmethods__["M"] = _ghmmwrapper.ghmm_cstate_M_get
    if _newclass:M = _swig_property(_ghmmwrapper.ghmm_cstate_M_get, _ghmmwrapper.ghmm_cstate_M_set)
    __swig_setmethods__["pi"] = _ghmmwrapper.ghmm_cstate_pi_set
    __swig_getmethods__["pi"] = _ghmmwrapper.ghmm_cstate_pi_get
    if _newclass:pi = _swig_property(_ghmmwrapper.ghmm_cstate_pi_get, _ghmmwrapper.ghmm_cstate_pi_set)
    __swig_setmethods__["out_id"] = _ghmmwrapper.ghmm_cstate_out_id_set
    __swig_getmethods__["out_id"] = _ghmmwrapper.ghmm_cstate_out_id_get
    if _newclass:out_id = _swig_property(_ghmmwrapper.ghmm_cstate_out_id_get, _ghmmwrapper.ghmm_cstate_out_id_set)
    __swig_setmethods__["in_id"] = _ghmmwrapper.ghmm_cstate_in_id_set
    __swig_getmethods__["in_id"] = _ghmmwrapper.ghmm_cstate_in_id_get
    if _newclass:in_id = _swig_property(_ghmmwrapper.ghmm_cstate_in_id_get, _ghmmwrapper.ghmm_cstate_in_id_set)
    __swig_setmethods__["out_a"] = _ghmmwrapper.ghmm_cstate_out_a_set
    __swig_getmethods__["out_a"] = _ghmmwrapper.ghmm_cstate_out_a_get
    if _newclass:out_a = _swig_property(_ghmmwrapper.ghmm_cstate_out_a_get, _ghmmwrapper.ghmm_cstate_out_a_set)
    __swig_setmethods__["in_a"] = _ghmmwrapper.ghmm_cstate_in_a_set
    __swig_getmethods__["in_a"] = _ghmmwrapper.ghmm_cstate_in_a_get
    if _newclass:in_a = _swig_property(_ghmmwrapper.ghmm_cstate_in_a_get, _ghmmwrapper.ghmm_cstate_in_a_set)
    __swig_setmethods__["out_states"] = _ghmmwrapper.ghmm_cstate_out_states_set
    __swig_getmethods__["out_states"] = _ghmmwrapper.ghmm_cstate_out_states_get
    if _newclass:out_states = _swig_property(_ghmmwrapper.ghmm_cstate_out_states_get, _ghmmwrapper.ghmm_cstate_out_states_set)
    __swig_setmethods__["in_states"] = _ghmmwrapper.ghmm_cstate_in_states_set
    __swig_getmethods__["in_states"] = _ghmmwrapper.ghmm_cstate_in_states_get
    if _newclass:in_states = _swig_property(_ghmmwrapper.ghmm_cstate_in_states_get, _ghmmwrapper.ghmm_cstate_in_states_set)
    __swig_setmethods__["c"] = _ghmmwrapper.ghmm_cstate_c_set
    __swig_getmethods__["c"] = _ghmmwrapper.ghmm_cstate_c_get
    if _newclass:c = _swig_property(_ghmmwrapper.ghmm_cstate_c_get, _ghmmwrapper.ghmm_cstate_c_set)
    __swig_setmethods__["fix"] = _ghmmwrapper.ghmm_cstate_fix_set
    __swig_getmethods__["fix"] = _ghmmwrapper.ghmm_cstate_fix_get
    if _newclass:fix = _swig_property(_ghmmwrapper.ghmm_cstate_fix_get, _ghmmwrapper.ghmm_cstate_fix_set)
    __swig_setmethods__["e"] = _ghmmwrapper.ghmm_cstate_e_set
    __swig_getmethods__["e"] = _ghmmwrapper.ghmm_cstate_e_get
    if _newclass:e = _swig_property(_ghmmwrapper.ghmm_cstate_e_get, _ghmmwrapper.ghmm_cstate_e_set)
    __swig_setmethods__["desc"] = _ghmmwrapper.ghmm_cstate_desc_set
    __swig_getmethods__["desc"] = _ghmmwrapper.ghmm_cstate_desc_get
    if _newclass:desc = _swig_property(_ghmmwrapper.ghmm_cstate_desc_get, _ghmmwrapper.ghmm_cstate_desc_set)
    __swig_setmethods__["xPosition"] = _ghmmwrapper.ghmm_cstate_xPosition_set
    __swig_getmethods__["xPosition"] = _ghmmwrapper.ghmm_cstate_xPosition_get
    if _newclass:xPosition = _swig_property(_ghmmwrapper.ghmm_cstate_xPosition_get, _ghmmwrapper.ghmm_cstate_xPosition_set)
    __swig_setmethods__["yPosition"] = _ghmmwrapper.ghmm_cstate_yPosition_set
    __swig_getmethods__["yPosition"] = _ghmmwrapper.ghmm_cstate_yPosition_get
    if _newclass:yPosition = _swig_property(_ghmmwrapper.ghmm_cstate_yPosition_get, _ghmmwrapper.ghmm_cstate_yPosition_set)
    def alloc(self, *args): return _ghmmwrapper.ghmm_cstate_alloc(self, *args)
    def setDensity(self, *args): return _ghmmwrapper.ghmm_cstate_setDensity(self, *args)
    def setWeight(self, *args): return _ghmmwrapper.ghmm_cstate_setWeight(self, *args)
    def setMean(self, *args): return _ghmmwrapper.ghmm_cstate_setMean(self, *args)
    def setStdDev(self, *args): return _ghmmwrapper.ghmm_cstate_setStdDev(self, *args)
    def getDensity(self, *args): return _ghmmwrapper.ghmm_cstate_getDensity(self, *args)
    def getWeight(self, *args): return _ghmmwrapper.ghmm_cstate_getWeight(self, *args)
    def getMean(self, *args): return _ghmmwrapper.ghmm_cstate_getMean(self, *args)
    def getStdDev(self, *args): return _ghmmwrapper.ghmm_cstate_getStdDev(self, *args)
    def setMin(self, *args): return _ghmmwrapper.ghmm_cstate_setMin(self, *args)
    def setMax(self, *args): return _ghmmwrapper.ghmm_cstate_setMax(self, *args)
    def getInState(self, *args): return _ghmmwrapper.ghmm_cstate_getInState(self, *args)
    def getOutState(self, *args): return _ghmmwrapper.ghmm_cstate_getOutState(self, *args)
    def getInProb(self, *args): return _ghmmwrapper.ghmm_cstate_getInProb(self, *args)
    def getOutProb(self, *args): return _ghmmwrapper.ghmm_cstate_getOutProb(self, *args)
    def setInProb(self, *args): return _ghmmwrapper.ghmm_cstate_setInProb(self, *args)
    def setOutProb(self, *args): return _ghmmwrapper.ghmm_cstate_setOutProb(self, *args)
    def getEmission(self, *args): return _ghmmwrapper.ghmm_cstate_getEmission(self, *args)
    def calc_cmbm(self, *args): return _ghmmwrapper.ghmm_cstate_calc_cmbm(self, *args)
    def calc_b(self, *args): return _ghmmwrapper.ghmm_cstate_calc_b(self, *args)
    def calc_cmBm(self, *args): return _ghmmwrapper.ghmm_cstate_calc_cmBm(self, *args)
    def calc_B(self, *args): return _ghmmwrapper.ghmm_cstate_calc_B(self, *args)
    def getDesc(self): return _ghmmwrapper.ghmm_cstate_getDesc(self)
    def setDesc(self, *args): return _ghmmwrapper.ghmm_cstate_setDesc(self, *args)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_cstate()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_cstate
    __del__ = lambda self : None;
ghmm_cstate_swigregister = _ghmmwrapper.ghmm_cstate_swigregister
ghmm_cstate_swigregister(ghmm_cstate)


def cstate_array_alloc(*args):
  return _ghmmwrapper.cstate_array_alloc(*args)
cstate_array_alloc = _ghmmwrapper.cstate_array_alloc

def cstate_array_getRef(*args):
  return _ghmmwrapper.cstate_array_getRef(*args)
cstate_array_getRef = _ghmmwrapper.cstate_array_getRef

def cstate_ptr_array_alloc(*args):
  return _ghmmwrapper.cstate_ptr_array_alloc(*args)
cstate_ptr_array_alloc = _ghmmwrapper.cstate_ptr_array_alloc

def cstate_ptr_array_getitem(*args):
  return _ghmmwrapper.cstate_ptr_array_getitem(*args)
cstate_ptr_array_getitem = _ghmmwrapper.cstate_ptr_array_getitem

def cstate_ptr_array_setitem(*args):
  return _ghmmwrapper.cstate_ptr_array_setitem(*args)
cstate_ptr_array_setitem = _ghmmwrapper.cstate_ptr_array_setitem
class ghmm_cmodel_class_change_context(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_cmodel_class_change_context, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_cmodel_class_change_context, name)
    __repr__ = _swig_repr
    __swig_setmethods__["python_module"] = _ghmmwrapper.ghmm_cmodel_class_change_context_python_module_set
    __swig_getmethods__["python_module"] = _ghmmwrapper.ghmm_cmodel_class_change_context_python_module_get
    if _newclass:python_module = _swig_property(_ghmmwrapper.ghmm_cmodel_class_change_context_python_module_get, _ghmmwrapper.ghmm_cmodel_class_change_context_python_module_set)
    __swig_setmethods__["python_function"] = _ghmmwrapper.ghmm_cmodel_class_change_context_python_function_set
    __swig_getmethods__["python_function"] = _ghmmwrapper.ghmm_cmodel_class_change_context_python_function_get
    if _newclass:python_function = _swig_property(_ghmmwrapper.ghmm_cmodel_class_change_context_python_function_get, _ghmmwrapper.ghmm_cmodel_class_change_context_python_function_set)
    __swig_setmethods__["k"] = _ghmmwrapper.ghmm_cmodel_class_change_context_k_set
    __swig_getmethods__["k"] = _ghmmwrapper.ghmm_cmodel_class_change_context_k_get
    if _newclass:k = _swig_property(_ghmmwrapper.ghmm_cmodel_class_change_context_k_get, _ghmmwrapper.ghmm_cmodel_class_change_context_k_set)
    __swig_setmethods__["get_class"] = _ghmmwrapper.ghmm_cmodel_class_change_context_get_class_set
    __swig_getmethods__["get_class"] = _ghmmwrapper.ghmm_cmodel_class_change_context_get_class_get
    if _newclass:get_class = _swig_property(_ghmmwrapper.ghmm_cmodel_class_change_context_get_class_get, _ghmmwrapper.ghmm_cmodel_class_change_context_get_class_set)
    __swig_setmethods__["user_data"] = _ghmmwrapper.ghmm_cmodel_class_change_context_user_data_set
    __swig_getmethods__["user_data"] = _ghmmwrapper.ghmm_cmodel_class_change_context_user_data_get
    if _newclass:user_data = _swig_property(_ghmmwrapper.ghmm_cmodel_class_change_context_user_data_get, _ghmmwrapper.ghmm_cmodel_class_change_context_user_data_set)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_cmodel_class_change_context()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_cmodel_class_change_context
    __del__ = lambda self : None;
ghmm_cmodel_class_change_context_swigregister = _ghmmwrapper.ghmm_cmodel_class_change_context_swigregister
ghmm_cmodel_class_change_context_swigregister(ghmm_cmodel_class_change_context)

class ghmm_cmodel_baum_welch_context(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_cmodel_baum_welch_context, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_cmodel_baum_welch_context, name)
    __repr__ = _swig_repr
    __swig_setmethods__["smo"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_smo_set
    __swig_getmethods__["smo"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_smo_get
    if _newclass:smo = _swig_property(_ghmmwrapper.ghmm_cmodel_baum_welch_context_smo_get, _ghmmwrapper.ghmm_cmodel_baum_welch_context_smo_set)
    __swig_setmethods__["sqd"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_sqd_set
    __swig_getmethods__["sqd"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_sqd_get
    if _newclass:sqd = _swig_property(_ghmmwrapper.ghmm_cmodel_baum_welch_context_sqd_get, _ghmmwrapper.ghmm_cmodel_baum_welch_context_sqd_set)
    __swig_setmethods__["logp"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_logp_set
    __swig_getmethods__["logp"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_logp_get
    if _newclass:logp = _swig_property(_ghmmwrapper.ghmm_cmodel_baum_welch_context_logp_get, _ghmmwrapper.ghmm_cmodel_baum_welch_context_logp_set)
    __swig_setmethods__["eps"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_eps_set
    __swig_getmethods__["eps"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_eps_get
    if _newclass:eps = _swig_property(_ghmmwrapper.ghmm_cmodel_baum_welch_context_eps_get, _ghmmwrapper.ghmm_cmodel_baum_welch_context_eps_set)
    __swig_setmethods__["max_iter"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_max_iter_set
    __swig_getmethods__["max_iter"] = _ghmmwrapper.ghmm_cmodel_baum_welch_context_max_iter_get
    if _newclass:max_iter = _swig_property(_ghmmwrapper.ghmm_cmodel_baum_welch_context_max_iter_get, _ghmmwrapper.ghmm_cmodel_baum_welch_context_max_iter_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_cmodel_baum_welch_context(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_cmodel_baum_welch_context
    __del__ = lambda self : None;
ghmm_cmodel_baum_welch_context_swigregister = _ghmmwrapper.ghmm_cmodel_baum_welch_context_swigregister
ghmm_cmodel_baum_welch_context_swigregister(ghmm_cmodel_baum_welch_context)

class ghmm_cmodel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_cmodel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_cmodel, name)
    __repr__ = _swig_repr
    __swig_setmethods__["N"] = _ghmmwrapper.ghmm_cmodel_N_set
    __swig_getmethods__["N"] = _ghmmwrapper.ghmm_cmodel_N_get
    if _newclass:N = _swig_property(_ghmmwrapper.ghmm_cmodel_N_get, _ghmmwrapper.ghmm_cmodel_N_set)
    __swig_setmethods__["M"] = _ghmmwrapper.ghmm_cmodel_M_set
    __swig_getmethods__["M"] = _ghmmwrapper.ghmm_cmodel_M_get
    if _newclass:M = _swig_property(_ghmmwrapper.ghmm_cmodel_M_get, _ghmmwrapper.ghmm_cmodel_M_set)
    __swig_setmethods__["dim"] = _ghmmwrapper.ghmm_cmodel_dim_set
    __swig_getmethods__["dim"] = _ghmmwrapper.ghmm_cmodel_dim_get
    if _newclass:dim = _swig_property(_ghmmwrapper.ghmm_cmodel_dim_get, _ghmmwrapper.ghmm_cmodel_dim_set)
    __swig_setmethods__["cos"] = _ghmmwrapper.ghmm_cmodel_cos_set
    __swig_getmethods__["cos"] = _ghmmwrapper.ghmm_cmodel_cos_get
    if _newclass:cos = _swig_property(_ghmmwrapper.ghmm_cmodel_cos_get, _ghmmwrapper.ghmm_cmodel_cos_set)
    __swig_setmethods__["prior"] = _ghmmwrapper.ghmm_cmodel_prior_set
    __swig_getmethods__["prior"] = _ghmmwrapper.ghmm_cmodel_prior_get
    if _newclass:prior = _swig_property(_ghmmwrapper.ghmm_cmodel_prior_get, _ghmmwrapper.ghmm_cmodel_prior_set)
    __swig_setmethods__["name"] = _ghmmwrapper.ghmm_cmodel_name_set
    __swig_getmethods__["name"] = _ghmmwrapper.ghmm_cmodel_name_get
    if _newclass:name = _swig_property(_ghmmwrapper.ghmm_cmodel_name_get, _ghmmwrapper.ghmm_cmodel_name_set)
    __swig_setmethods__["model_type"] = _ghmmwrapper.ghmm_cmodel_model_type_set
    __swig_getmethods__["model_type"] = _ghmmwrapper.ghmm_cmodel_model_type_get
    if _newclass:model_type = _swig_property(_ghmmwrapper.ghmm_cmodel_model_type_get, _ghmmwrapper.ghmm_cmodel_model_type_set)
    __swig_setmethods__["s"] = _ghmmwrapper.ghmm_cmodel_s_set
    __swig_getmethods__["s"] = _ghmmwrapper.ghmm_cmodel_s_get
    if _newclass:s = _swig_property(_ghmmwrapper.ghmm_cmodel_s_get, _ghmmwrapper.ghmm_cmodel_s_set)
    __swig_setmethods__["class_change"] = _ghmmwrapper.ghmm_cmodel_class_change_set
    __swig_getmethods__["class_change"] = _ghmmwrapper.ghmm_cmodel_class_change_get
    if _newclass:class_change = _swig_property(_ghmmwrapper.ghmm_cmodel_class_change_get, _ghmmwrapper.ghmm_cmodel_class_change_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_cmodel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_cmodel
    __del__ = lambda self : None;
    def write_xml(self, *args): return _ghmmwrapper.ghmm_cmodel_write_xml(self, *args)
    def forward(self, *args): return _ghmmwrapper.ghmm_cmodel_forward(self, *args)
    def backward(self, *args): return _ghmmwrapper.ghmm_cmodel_backward(self, *args)
    def logp(self, *args): return _ghmmwrapper.ghmm_cmodel_logp(self, *args)
    def logp_joint(self, *args): return _ghmmwrapper.ghmm_cmodel_logp_joint(self, *args)
    def class_change_alloc(self, *args): return _ghmmwrapper.ghmm_cmodel_class_change_alloc(self, *args)
    def get_random_var(self, *args): return _ghmmwrapper.ghmm_cmodel_get_random_var(self, *args)
    def generate_sequences(self, *args): return _ghmmwrapper.ghmm_cmodel_generate_sequences(self, *args)
    def likelihood(self, *args): return _ghmmwrapper.ghmm_cmodel_likelihood(self, *args)
    def individual_likelihoods(self, *args): return _ghmmwrapper.ghmm_cmodel_individual_likelihoods(self, *args)
    def prob_distance(self, *args): return _ghmmwrapper.ghmm_cmodel_prob_distance(self, *args)
    def get_interval_B(self, *args): return _ghmmwrapper.ghmm_cmodel_get_interval_B(self, *args)
    def normalize(self): return _ghmmwrapper.ghmm_cmodel_normalize(self)
    def get_transition(self, *args): return _ghmmwrapper.ghmm_cmodel_get_transition(self, *args)
    def check_transition(self, *args): return _ghmmwrapper.ghmm_cmodel_check_transition(self, *args)
    def set_transition(self, *args): return _ghmmwrapper.ghmm_cmodel_set_transition(self, *args)
    def viterbi(self, *args): return _ghmmwrapper.ghmm_cmodel_viterbi(self, *args)
    def getState(self, *args): return _ghmmwrapper.ghmm_cmodel_getState(self, *args)
    def addModelTypeFlags(self, *args): return _ghmmwrapper.ghmm_cmodel_addModelTypeFlags(self, *args)
    def removeModelTypeFlags(self, *args): return _ghmmwrapper.ghmm_cmodel_removeModelTypeFlags(self, *args)
    def getStateName(self, *args): return _ghmmwrapper.ghmm_cmodel_getStateName(self, *args)
    def setStateName(self, *args): return _ghmmwrapper.ghmm_cmodel_setStateName(self, *args)
ghmm_cmodel_swigregister = _ghmmwrapper.ghmm_cmodel_swigregister
ghmm_cmodel_swigregister(ghmm_cmodel)


def ghmm_cmodel_free(*args):
  return _ghmmwrapper.ghmm_cmodel_free(*args)
ghmm_cmodel_free = _ghmmwrapper.ghmm_cmodel_free

def ghmm_cmodel_xml_write(*args):
  return _ghmmwrapper.ghmm_cmodel_xml_write(*args)
ghmm_cmodel_xml_write = _ghmmwrapper.ghmm_cmodel_xml_write

def ghmm_cmodel_baum_welch(*args):
  return _ghmmwrapper.ghmm_cmodel_baum_welch(*args)
ghmm_cmodel_baum_welch = _ghmmwrapper.ghmm_cmodel_baum_welch

def cmodel_array_alloc(*args):
  return _ghmmwrapper.cmodel_array_alloc(*args)
cmodel_array_alloc = _ghmmwrapper.cmodel_array_alloc

def cmodel_array_getRef(*args):
  return _ghmmwrapper.cmodel_array_getRef(*args)
cmodel_array_getRef = _ghmmwrapper.cmodel_array_getRef

def cmodel_ptr_array_alloc(*args):
  return _ghmmwrapper.cmodel_ptr_array_alloc(*args)
cmodel_ptr_array_alloc = _ghmmwrapper.cmodel_ptr_array_alloc

def cmodel_ptr_array_getitem(*args):
  return _ghmmwrapper.cmodel_ptr_array_getitem(*args)
cmodel_ptr_array_getitem = _ghmmwrapper.cmodel_ptr_array_getitem

def cmodel_ptr_array_setitem(*args):
  return _ghmmwrapper.cmodel_ptr_array_setitem(*args)
cmodel_ptr_array_setitem = _ghmmwrapper.cmodel_ptr_array_setitem
class ghmm_dbackground(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dbackground, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dbackground, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _ghmmwrapper.ghmm_dbackground_n_set
    __swig_getmethods__["n"] = _ghmmwrapper.ghmm_dbackground_n_get
    if _newclass:n = _swig_property(_ghmmwrapper.ghmm_dbackground_n_get, _ghmmwrapper.ghmm_dbackground_n_set)
    __swig_setmethods__["m"] = _ghmmwrapper.ghmm_dbackground_m_set
    __swig_getmethods__["m"] = _ghmmwrapper.ghmm_dbackground_m_get
    if _newclass:m = _swig_property(_ghmmwrapper.ghmm_dbackground_m_get, _ghmmwrapper.ghmm_dbackground_m_set)
    __swig_setmethods__["order"] = _ghmmwrapper.ghmm_dbackground_order_set
    __swig_getmethods__["order"] = _ghmmwrapper.ghmm_dbackground_order_get
    if _newclass:order = _swig_property(_ghmmwrapper.ghmm_dbackground_order_get, _ghmmwrapper.ghmm_dbackground_order_set)
    __swig_setmethods__["b"] = _ghmmwrapper.ghmm_dbackground_b_set
    __swig_getmethods__["b"] = _ghmmwrapper.ghmm_dbackground_b_get
    if _newclass:b = _swig_property(_ghmmwrapper.ghmm_dbackground_b_get, _ghmmwrapper.ghmm_dbackground_b_set)
    __swig_setmethods__["name"] = _ghmmwrapper.ghmm_dbackground_name_set
    __swig_getmethods__["name"] = _ghmmwrapper.ghmm_dbackground_name_get
    if _newclass:name = _swig_property(_ghmmwrapper.ghmm_dbackground_name_get, _ghmmwrapper.ghmm_dbackground_name_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_dbackground(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dbackground
    __del__ = lambda self : None;
    def copy(self): return _ghmmwrapper.ghmm_dbackground_copy(self)
    def getOrder(self, *args): return _ghmmwrapper.ghmm_dbackground_getOrder(self, *args)
    def getWeights(self, *args): return _ghmmwrapper.ghmm_dbackground_getWeights(self, *args)
    def getName(self, *args): return _ghmmwrapper.ghmm_dbackground_getName(self, *args)
    def setName(self, *args): return _ghmmwrapper.ghmm_dbackground_setName(self, *args)
ghmm_dbackground_swigregister = _ghmmwrapper.ghmm_dbackground_swigregister
ghmm_dbackground_swigregister(ghmm_dbackground)


def ghmm_dbackground_alloc(*args):
  return _ghmmwrapper.ghmm_dbackground_alloc(*args)
ghmm_dbackground_alloc = _ghmmwrapper.ghmm_dbackground_alloc
class ghmm_dstate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dstate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dstate, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pi"] = _ghmmwrapper.ghmm_dstate_pi_set
    __swig_getmethods__["pi"] = _ghmmwrapper.ghmm_dstate_pi_get
    if _newclass:pi = _swig_property(_ghmmwrapper.ghmm_dstate_pi_get, _ghmmwrapper.ghmm_dstate_pi_set)
    __swig_setmethods__["b"] = _ghmmwrapper.ghmm_dstate_b_set
    __swig_getmethods__["b"] = _ghmmwrapper.ghmm_dstate_b_get
    if _newclass:b = _swig_property(_ghmmwrapper.ghmm_dstate_b_get, _ghmmwrapper.ghmm_dstate_b_set)
    __swig_setmethods__["out_id"] = _ghmmwrapper.ghmm_dstate_out_id_set
    __swig_getmethods__["out_id"] = _ghmmwrapper.ghmm_dstate_out_id_get
    if _newclass:out_id = _swig_property(_ghmmwrapper.ghmm_dstate_out_id_get, _ghmmwrapper.ghmm_dstate_out_id_set)
    __swig_setmethods__["in_id"] = _ghmmwrapper.ghmm_dstate_in_id_set
    __swig_getmethods__["in_id"] = _ghmmwrapper.ghmm_dstate_in_id_get
    if _newclass:in_id = _swig_property(_ghmmwrapper.ghmm_dstate_in_id_get, _ghmmwrapper.ghmm_dstate_in_id_set)
    __swig_setmethods__["out_a"] = _ghmmwrapper.ghmm_dstate_out_a_set
    __swig_getmethods__["out_a"] = _ghmmwrapper.ghmm_dstate_out_a_get
    if _newclass:out_a = _swig_property(_ghmmwrapper.ghmm_dstate_out_a_get, _ghmmwrapper.ghmm_dstate_out_a_set)
    __swig_setmethods__["in_a"] = _ghmmwrapper.ghmm_dstate_in_a_set
    __swig_getmethods__["in_a"] = _ghmmwrapper.ghmm_dstate_in_a_get
    if _newclass:in_a = _swig_property(_ghmmwrapper.ghmm_dstate_in_a_get, _ghmmwrapper.ghmm_dstate_in_a_set)
    __swig_setmethods__["out_states"] = _ghmmwrapper.ghmm_dstate_out_states_set
    __swig_getmethods__["out_states"] = _ghmmwrapper.ghmm_dstate_out_states_get
    if _newclass:out_states = _swig_property(_ghmmwrapper.ghmm_dstate_out_states_get, _ghmmwrapper.ghmm_dstate_out_states_set)
    __swig_setmethods__["in_states"] = _ghmmwrapper.ghmm_dstate_in_states_set
    __swig_getmethods__["in_states"] = _ghmmwrapper.ghmm_dstate_in_states_get
    if _newclass:in_states = _swig_property(_ghmmwrapper.ghmm_dstate_in_states_get, _ghmmwrapper.ghmm_dstate_in_states_set)
    __swig_setmethods__["fix"] = _ghmmwrapper.ghmm_dstate_fix_set
    __swig_getmethods__["fix"] = _ghmmwrapper.ghmm_dstate_fix_get
    if _newclass:fix = _swig_property(_ghmmwrapper.ghmm_dstate_fix_get, _ghmmwrapper.ghmm_dstate_fix_set)
    __swig_setmethods__["desc"] = _ghmmwrapper.ghmm_dstate_desc_set
    __swig_getmethods__["desc"] = _ghmmwrapper.ghmm_dstate_desc_get
    if _newclass:desc = _swig_property(_ghmmwrapper.ghmm_dstate_desc_get, _ghmmwrapper.ghmm_dstate_desc_set)
    __swig_setmethods__["xPosition"] = _ghmmwrapper.ghmm_dstate_xPosition_set
    __swig_getmethods__["xPosition"] = _ghmmwrapper.ghmm_dstate_xPosition_get
    if _newclass:xPosition = _swig_property(_ghmmwrapper.ghmm_dstate_xPosition_get, _ghmmwrapper.ghmm_dstate_xPosition_set)
    __swig_setmethods__["yPosition"] = _ghmmwrapper.ghmm_dstate_yPosition_set
    __swig_getmethods__["yPosition"] = _ghmmwrapper.ghmm_dstate_yPosition_get
    if _newclass:yPosition = _swig_property(_ghmmwrapper.ghmm_dstate_yPosition_get, _ghmmwrapper.ghmm_dstate_yPosition_set)
    def clean(self): return _ghmmwrapper.ghmm_dstate_clean(self)
    def getInState(self, *args): return _ghmmwrapper.ghmm_dstate_getInState(self, *args)
    def getOutState(self, *args): return _ghmmwrapper.ghmm_dstate_getOutState(self, *args)
    def getInProb(self, *args): return _ghmmwrapper.ghmm_dstate_getInProb(self, *args)
    def getOutProb(self, *args): return _ghmmwrapper.ghmm_dstate_getOutProb(self, *args)
    def getDesc(self): return _ghmmwrapper.ghmm_dstate_getDesc(self)
    def setDesc(self, *args): return _ghmmwrapper.ghmm_dstate_setDesc(self, *args)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_dstate()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dstate
    __del__ = lambda self : None;
ghmm_dstate_swigregister = _ghmmwrapper.ghmm_dstate_swigregister
ghmm_dstate_swigregister(ghmm_dstate)


def dstate_array_alloc(*args):
  return _ghmmwrapper.dstate_array_alloc(*args)
dstate_array_alloc = _ghmmwrapper.dstate_array_alloc

def dstate_array_getRef(*args):
  return _ghmmwrapper.dstate_array_getRef(*args)
dstate_array_getRef = _ghmmwrapper.dstate_array_getRef

def dstate_ptr_array_alloc(*args):
  return _ghmmwrapper.dstate_ptr_array_alloc(*args)
dstate_ptr_array_alloc = _ghmmwrapper.dstate_ptr_array_alloc

def dstate_ptr_array_getitem(*args):
  return _ghmmwrapper.dstate_ptr_array_getitem(*args)
dstate_ptr_array_getitem = _ghmmwrapper.dstate_ptr_array_getitem

def dstate_ptr_array_setitem(*args):
  return _ghmmwrapper.dstate_ptr_array_setitem(*args)
dstate_ptr_array_setitem = _ghmmwrapper.dstate_ptr_array_setitem
class ghmm_dmodel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dmodel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dmodel, name)
    __repr__ = _swig_repr
    __swig_setmethods__["N"] = _ghmmwrapper.ghmm_dmodel_N_set
    __swig_getmethods__["N"] = _ghmmwrapper.ghmm_dmodel_N_get
    if _newclass:N = _swig_property(_ghmmwrapper.ghmm_dmodel_N_get, _ghmmwrapper.ghmm_dmodel_N_set)
    __swig_setmethods__["M"] = _ghmmwrapper.ghmm_dmodel_M_set
    __swig_getmethods__["M"] = _ghmmwrapper.ghmm_dmodel_M_get
    if _newclass:M = _swig_property(_ghmmwrapper.ghmm_dmodel_M_get, _ghmmwrapper.ghmm_dmodel_M_set)
    __swig_setmethods__["s"] = _ghmmwrapper.ghmm_dmodel_s_set
    __swig_getmethods__["s"] = _ghmmwrapper.ghmm_dmodel_s_get
    if _newclass:s = _swig_property(_ghmmwrapper.ghmm_dmodel_s_get, _ghmmwrapper.ghmm_dmodel_s_set)
    __swig_setmethods__["prior"] = _ghmmwrapper.ghmm_dmodel_prior_set
    __swig_getmethods__["prior"] = _ghmmwrapper.ghmm_dmodel_prior_get
    if _newclass:prior = _swig_property(_ghmmwrapper.ghmm_dmodel_prior_get, _ghmmwrapper.ghmm_dmodel_prior_set)
    __swig_setmethods__["name"] = _ghmmwrapper.ghmm_dmodel_name_set
    __swig_getmethods__["name"] = _ghmmwrapper.ghmm_dmodel_name_get
    if _newclass:name = _swig_property(_ghmmwrapper.ghmm_dmodel_name_get, _ghmmwrapper.ghmm_dmodel_name_set)
    __swig_setmethods__["model_type"] = _ghmmwrapper.ghmm_dmodel_model_type_set
    __swig_getmethods__["model_type"] = _ghmmwrapper.ghmm_dmodel_model_type_get
    if _newclass:model_type = _swig_property(_ghmmwrapper.ghmm_dmodel_model_type_get, _ghmmwrapper.ghmm_dmodel_model_type_set)
    __swig_setmethods__["silent"] = _ghmmwrapper.ghmm_dmodel_silent_set
    __swig_getmethods__["silent"] = _ghmmwrapper.ghmm_dmodel_silent_get
    if _newclass:silent = _swig_property(_ghmmwrapper.ghmm_dmodel_silent_get, _ghmmwrapper.ghmm_dmodel_silent_set)
    __swig_setmethods__["maxorder"] = _ghmmwrapper.ghmm_dmodel_maxorder_set
    __swig_getmethods__["maxorder"] = _ghmmwrapper.ghmm_dmodel_maxorder_get
    if _newclass:maxorder = _swig_property(_ghmmwrapper.ghmm_dmodel_maxorder_get, _ghmmwrapper.ghmm_dmodel_maxorder_set)
    __swig_setmethods__["emission_history"] = _ghmmwrapper.ghmm_dmodel_emission_history_set
    __swig_getmethods__["emission_history"] = _ghmmwrapper.ghmm_dmodel_emission_history_get
    if _newclass:emission_history = _swig_property(_ghmmwrapper.ghmm_dmodel_emission_history_get, _ghmmwrapper.ghmm_dmodel_emission_history_set)
    __swig_setmethods__["tied_to"] = _ghmmwrapper.ghmm_dmodel_tied_to_set
    __swig_getmethods__["tied_to"] = _ghmmwrapper.ghmm_dmodel_tied_to_get
    if _newclass:tied_to = _swig_property(_ghmmwrapper.ghmm_dmodel_tied_to_get, _ghmmwrapper.ghmm_dmodel_tied_to_set)
    __swig_setmethods__["order"] = _ghmmwrapper.ghmm_dmodel_order_set
    __swig_getmethods__["order"] = _ghmmwrapper.ghmm_dmodel_order_get
    if _newclass:order = _swig_property(_ghmmwrapper.ghmm_dmodel_order_get, _ghmmwrapper.ghmm_dmodel_order_set)
    __swig_setmethods__["background_id"] = _ghmmwrapper.ghmm_dmodel_background_id_set
    __swig_getmethods__["background_id"] = _ghmmwrapper.ghmm_dmodel_background_id_get
    if _newclass:background_id = _swig_property(_ghmmwrapper.ghmm_dmodel_background_id_get, _ghmmwrapper.ghmm_dmodel_background_id_set)
    __swig_setmethods__["bp"] = _ghmmwrapper.ghmm_dmodel_bp_set
    __swig_getmethods__["bp"] = _ghmmwrapper.ghmm_dmodel_bp_get
    if _newclass:bp = _swig_property(_ghmmwrapper.ghmm_dmodel_bp_get, _ghmmwrapper.ghmm_dmodel_bp_set)
    __swig_setmethods__["topo_order"] = _ghmmwrapper.ghmm_dmodel_topo_order_set
    __swig_getmethods__["topo_order"] = _ghmmwrapper.ghmm_dmodel_topo_order_get
    if _newclass:topo_order = _swig_property(_ghmmwrapper.ghmm_dmodel_topo_order_get, _ghmmwrapper.ghmm_dmodel_topo_order_set)
    __swig_setmethods__["topo_order_length"] = _ghmmwrapper.ghmm_dmodel_topo_order_length_set
    __swig_getmethods__["topo_order_length"] = _ghmmwrapper.ghmm_dmodel_topo_order_length_get
    if _newclass:topo_order_length = _swig_property(_ghmmwrapper.ghmm_dmodel_topo_order_length_get, _ghmmwrapper.ghmm_dmodel_topo_order_length_set)
    __swig_setmethods__["pow_lookup"] = _ghmmwrapper.ghmm_dmodel_pow_lookup_set
    __swig_getmethods__["pow_lookup"] = _ghmmwrapper.ghmm_dmodel_pow_lookup_get
    if _newclass:pow_lookup = _swig_property(_ghmmwrapper.ghmm_dmodel_pow_lookup_get, _ghmmwrapper.ghmm_dmodel_pow_lookup_set)
    __swig_setmethods__["label"] = _ghmmwrapper.ghmm_dmodel_label_set
    __swig_getmethods__["label"] = _ghmmwrapper.ghmm_dmodel_label_get
    if _newclass:label = _swig_property(_ghmmwrapper.ghmm_dmodel_label_get, _ghmmwrapper.ghmm_dmodel_label_set)
    __swig_setmethods__["label_alphabet"] = _ghmmwrapper.ghmm_dmodel_label_alphabet_set
    __swig_getmethods__["label_alphabet"] = _ghmmwrapper.ghmm_dmodel_label_alphabet_get
    if _newclass:label_alphabet = _swig_property(_ghmmwrapper.ghmm_dmodel_label_alphabet_get, _ghmmwrapper.ghmm_dmodel_label_alphabet_set)
    __swig_setmethods__["alphabet"] = _ghmmwrapper.ghmm_dmodel_alphabet_set
    __swig_getmethods__["alphabet"] = _ghmmwrapper.ghmm_dmodel_alphabet_get
    if _newclass:alphabet = _swig_property(_ghmmwrapper.ghmm_dmodel_alphabet_get, _ghmmwrapper.ghmm_dmodel_alphabet_set)
    def __init__(self, *args): 
        this = _ghmmwrapper.new_ghmm_dmodel(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dmodel
    __del__ = lambda self : None;
    def write_xml(self, *args): return _ghmmwrapper.ghmm_dmodel_write_xml(self, *args)
    def forward_init(self, *args): return _ghmmwrapper.ghmm_dmodel_forward_init(self, *args)
    def forward(self, *args): return _ghmmwrapper.ghmm_dmodel_forward(self, *args)
    def backward(self, *args): return _ghmmwrapper.ghmm_dmodel_backward(self, *args)
    def backward_termination(self, *args): return _ghmmwrapper.ghmm_dmodel_backward_termination(self, *args)
    def logp(self, *args): return _ghmmwrapper.ghmm_dmodel_logp(self, *args)
    def logp_joint(self, *args): return _ghmmwrapper.ghmm_dmodel_logp_joint(self, *args)
    def forward_lean(self, *args): return _ghmmwrapper.ghmm_dmodel_forward_lean(self, *args)
    def generate_sequences(self, *args): return _ghmmwrapper.ghmm_dmodel_generate_sequences(self, *args)
    def likelihood(self, *args): return _ghmmwrapper.ghmm_dmodel_likelihood(self, *args)
    def get_transition(self, *args): return _ghmmwrapper.ghmm_dmodel_get_transition(self, *args)
    def check_transition(self, *args): return _ghmmwrapper.ghmm_dmodel_check_transition(self, *args)
    def set_transition(self, *args): return _ghmmwrapper.ghmm_dmodel_set_transition(self, *args)
    def prob_distance(self, *args): return _ghmmwrapper.ghmm_dmodel_prob_distance(self, *args)
    def normalize(self, *args): return _ghmmwrapper.ghmm_dmodel_normalize(self, *args)
    def add_noise(self, *args): return _ghmmwrapper.ghmm_dmodel_add_noise(self, *args)
    def duration_apply(self, *args): return _ghmmwrapper.ghmm_dmodel_duration_apply(self, *args)
    def background_apply(self, *args): return _ghmmwrapper.ghmm_dmodel_background_apply(self, *args)
    def get_uniform_background(self, *args): return _ghmmwrapper.ghmm_dmodel_get_uniform_background(self, *args)
    def order_topological(self, *args): return _ghmmwrapper.ghmm_dmodel_order_topological(self, *args)
    def update_tie_groups(self, *args): return _ghmmwrapper.ghmm_dmodel_update_tie_groups(self, *args)
    def baum_welch(self, *args): return _ghmmwrapper.ghmm_dmodel_baum_welch(self, *args)
    def baum_welch_nstep(self, *args): return _ghmmwrapper.ghmm_dmodel_baum_welch_nstep(self, *args)
    def fbgibbs(self, *args): return _ghmmwrapper.ghmm_dmodel_fbgibbs(self, *args)
    def cfbgibbs(self, *args): return _ghmmwrapper.ghmm_dmodel_cfbgibbs(self, *args)
    def viterbi(self, *args): return _ghmmwrapper.ghmm_dmodel_viterbi(self, *args)
    def viterbi_logp(self, *args): return _ghmmwrapper.ghmm_dmodel_viterbi_logp(self, *args)
    def getState(self, *args): return _ghmmwrapper.ghmm_dmodel_getState(self, *args)
    def getSilent(self, *args): return _ghmmwrapper.ghmm_dmodel_getSilent(self, *args)
    def setSilent(self, *args): return _ghmmwrapper.ghmm_dmodel_setSilent(self, *args)
    def getTiedTo(self, *args): return _ghmmwrapper.ghmm_dmodel_getTiedTo(self, *args)
    def setTiedTo(self, *args): return _ghmmwrapper.ghmm_dmodel_setTiedTo(self, *args)
    def getOrder(self, *args): return _ghmmwrapper.ghmm_dmodel_getOrder(self, *args)
    def setOrder(self, *args): return _ghmmwrapper.ghmm_dmodel_setOrder(self, *args)
    def getBackgroundID(self, *args): return _ghmmwrapper.ghmm_dmodel_getBackgroundID(self, *args)
    def setBackgroundID(self, *args): return _ghmmwrapper.ghmm_dmodel_setBackgroundID(self, *args)
    def getStateLabel(self, *args): return _ghmmwrapper.ghmm_dmodel_getStateLabel(self, *args)
    def setStateLabel(self, *args): return _ghmmwrapper.ghmm_dmodel_setStateLabel(self, *args)
    def addModelTypeFlags(self, *args): return _ghmmwrapper.ghmm_dmodel_addModelTypeFlags(self, *args)
    def removeModelTypeFlags(self, *args): return _ghmmwrapper.ghmm_dmodel_removeModelTypeFlags(self, *args)
    def getStateName(self, *args): return _ghmmwrapper.ghmm_dmodel_getStateName(self, *args)
    def setStateName(self, *args): return _ghmmwrapper.ghmm_dmodel_setStateName(self, *args)
    def label_forward(self, *args): return _ghmmwrapper.ghmm_dmodel_label_forward(self, *args)
    def label_logp(self, *args): return _ghmmwrapper.ghmm_dmodel_label_logp(self, *args)
    def label_backward(self, *args): return _ghmmwrapper.ghmm_dmodel_label_backward(self, *args)
    def label_gradient_descent(self, *args): return _ghmmwrapper.ghmm_dmodel_label_gradient_descent(self, *args)
    def label_kbest(self, *args): return _ghmmwrapper.ghmm_dmodel_label_kbest(self, *args)
    def label_baum_welch(self, *args): return _ghmmwrapper.ghmm_dmodel_label_baum_welch(self, *args)
    def label_baum_welch_nstep(self, *args): return _ghmmwrapper.ghmm_dmodel_label_baum_welch_nstep(self, *args)
    def label_generate_sequences(self, *args): return _ghmmwrapper.ghmm_dmodel_label_generate_sequences(self, *args)
    def getLabel(self, *args): return _ghmmwrapper.ghmm_dmodel_getLabel(self, *args)
ghmm_dmodel_swigregister = _ghmmwrapper.ghmm_dmodel_swigregister
ghmm_dmodel_swigregister(ghmm_dmodel)


def ghmm_dmodel_free(*args):
  return _ghmmwrapper.ghmm_dmodel_free(*args)
ghmm_dmodel_free = _ghmmwrapper.ghmm_dmodel_free

def dmodel_array_alloc(*args):
  return _ghmmwrapper.dmodel_array_alloc(*args)
dmodel_array_alloc = _ghmmwrapper.dmodel_array_alloc

def dmodel_array_getRef(*args):
  return _ghmmwrapper.dmodel_array_getRef(*args)
dmodel_array_getRef = _ghmmwrapper.dmodel_array_getRef

def dmodel_ptr_array_alloc(*args):
  return _ghmmwrapper.dmodel_ptr_array_alloc(*args)
dmodel_ptr_array_alloc = _ghmmwrapper.dmodel_ptr_array_alloc

def dmodel_ptr_array_getitem(*args):
  return _ghmmwrapper.dmodel_ptr_array_getitem(*args)
dmodel_ptr_array_getitem = _ghmmwrapper.dmodel_ptr_array_getitem

def dmodel_ptr_array_setitem(*args):
  return _ghmmwrapper.dmodel_ptr_array_setitem(*args)
dmodel_ptr_array_setitem = _ghmmwrapper.dmodel_ptr_array_setitem

def ghmm_dmodel_label_discrim_perf(*args):
  return _ghmmwrapper.ghmm_dmodel_label_discrim_perf(*args)
ghmm_dmodel_label_discrim_perf = _ghmmwrapper.ghmm_dmodel_label_discrim_perf

def ghmm_dmodel_label_discriminative(*args):
  return _ghmmwrapper.ghmm_dmodel_label_discriminative(*args)
ghmm_dmodel_label_discriminative = _ghmmwrapper.ghmm_dmodel_label_discriminative
class ghmm_dpmodel_class_change_context(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dpmodel_class_change_context, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dpmodel_class_change_context, name)
    __repr__ = _swig_repr
    __swig_setmethods__["python_module"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_python_module_set
    __swig_getmethods__["python_module"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_python_module_get
    if _newclass:python_module = _swig_property(_ghmmwrapper.ghmm_dpmodel_class_change_context_python_module_get, _ghmmwrapper.ghmm_dpmodel_class_change_context_python_module_set)
    __swig_setmethods__["python_function"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_python_function_set
    __swig_getmethods__["python_function"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_python_function_get
    if _newclass:python_function = _swig_property(_ghmmwrapper.ghmm_dpmodel_class_change_context_python_function_get, _ghmmwrapper.ghmm_dpmodel_class_change_context_python_function_set)
    __swig_setmethods__["get_class"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_get_class_set
    __swig_getmethods__["get_class"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_get_class_get
    if _newclass:get_class = _swig_property(_ghmmwrapper.ghmm_dpmodel_class_change_context_get_class_get, _ghmmwrapper.ghmm_dpmodel_class_change_context_get_class_set)
    __swig_setmethods__["user_data"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_user_data_set
    __swig_getmethods__["user_data"] = _ghmmwrapper.ghmm_dpmodel_class_change_context_user_data_get
    if _newclass:user_data = _swig_property(_ghmmwrapper.ghmm_dpmodel_class_change_context_user_data_get, _ghmmwrapper.ghmm_dpmodel_class_change_context_user_data_set)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_dpmodel_class_change_context()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dpmodel_class_change_context
    __del__ = lambda self : None;
ghmm_dpmodel_class_change_context_swigregister = _ghmmwrapper.ghmm_dpmodel_class_change_context_swigregister
ghmm_dpmodel_class_change_context_swigregister(ghmm_dpmodel_class_change_context)

class ghmm_dpstate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dpstate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dpstate, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pi"] = _ghmmwrapper.ghmm_dpstate_pi_set
    __swig_getmethods__["pi"] = _ghmmwrapper.ghmm_dpstate_pi_get
    if _newclass:pi = _swig_property(_ghmmwrapper.ghmm_dpstate_pi_get, _ghmmwrapper.ghmm_dpstate_pi_set)
    __swig_setmethods__["log_pi"] = _ghmmwrapper.ghmm_dpstate_log_pi_set
    __swig_getmethods__["log_pi"] = _ghmmwrapper.ghmm_dpstate_log_pi_get
    if _newclass:log_pi = _swig_property(_ghmmwrapper.ghmm_dpstate_log_pi_get, _ghmmwrapper.ghmm_dpstate_log_pi_set)
    __swig_setmethods__["b"] = _ghmmwrapper.ghmm_dpstate_b_set
    __swig_getmethods__["b"] = _ghmmwrapper.ghmm_dpstate_b_get
    if _newclass:b = _swig_property(_ghmmwrapper.ghmm_dpstate_b_get, _ghmmwrapper.ghmm_dpstate_b_set)
    __swig_setmethods__["order"] = _ghmmwrapper.ghmm_dpstate_order_set
    __swig_getmethods__["order"] = _ghmmwrapper.ghmm_dpstate_order_get
    if _newclass:order = _swig_property(_ghmmwrapper.ghmm_dpstate_order_get, _ghmmwrapper.ghmm_dpstate_order_set)
    __swig_setmethods__["out_id"] = _ghmmwrapper.ghmm_dpstate_out_id_set
    __swig_getmethods__["out_id"] = _ghmmwrapper.ghmm_dpstate_out_id_get
    if _newclass:out_id = _swig_property(_ghmmwrapper.ghmm_dpstate_out_id_get, _ghmmwrapper.ghmm_dpstate_out_id_set)
    __swig_setmethods__["in_id"] = _ghmmwrapper.ghmm_dpstate_in_id_set
    __swig_getmethods__["in_id"] = _ghmmwrapper.ghmm_dpstate_in_id_get
    if _newclass:in_id = _swig_property(_ghmmwrapper.ghmm_dpstate_in_id_get, _ghmmwrapper.ghmm_dpstate_in_id_set)
    __swig_setmethods__["out_a"] = _ghmmwrapper.ghmm_dpstate_out_a_set
    __swig_getmethods__["out_a"] = _ghmmwrapper.ghmm_dpstate_out_a_get
    if _newclass:out_a = _swig_property(_ghmmwrapper.ghmm_dpstate_out_a_get, _ghmmwrapper.ghmm_dpstate_out_a_set)
    __swig_setmethods__["in_a"] = _ghmmwrapper.ghmm_dpstate_in_a_set
    __swig_getmethods__["in_a"] = _ghmmwrapper.ghmm_dpstate_in_a_get
    if _newclass:in_a = _swig_property(_ghmmwrapper.ghmm_dpstate_in_a_get, _ghmmwrapper.ghmm_dpstate_in_a_set)
    __swig_setmethods__["kclasses"] = _ghmmwrapper.ghmm_dpstate_kclasses_set
    __swig_getmethods__["kclasses"] = _ghmmwrapper.ghmm_dpstate_kclasses_get
    if _newclass:kclasses = _swig_property(_ghmmwrapper.ghmm_dpstate_kclasses_get, _ghmmwrapper.ghmm_dpstate_kclasses_set)
    __swig_setmethods__["class_change"] = _ghmmwrapper.ghmm_dpstate_class_change_set
    __swig_getmethods__["class_change"] = _ghmmwrapper.ghmm_dpstate_class_change_get
    if _newclass:class_change = _swig_property(_ghmmwrapper.ghmm_dpstate_class_change_get, _ghmmwrapper.ghmm_dpstate_class_change_set)
    __swig_setmethods__["out_states"] = _ghmmwrapper.ghmm_dpstate_out_states_set
    __swig_getmethods__["out_states"] = _ghmmwrapper.ghmm_dpstate_out_states_get
    if _newclass:out_states = _swig_property(_ghmmwrapper.ghmm_dpstate_out_states_get, _ghmmwrapper.ghmm_dpstate_out_states_set)
    __swig_setmethods__["in_states"] = _ghmmwrapper.ghmm_dpstate_in_states_set
    __swig_getmethods__["in_states"] = _ghmmwrapper.ghmm_dpstate_in_states_get
    if _newclass:in_states = _swig_property(_ghmmwrapper.ghmm_dpstate_in_states_get, _ghmmwrapper.ghmm_dpstate_in_states_set)
    __swig_setmethods__["fix"] = _ghmmwrapper.ghmm_dpstate_fix_set
    __swig_getmethods__["fix"] = _ghmmwrapper.ghmm_dpstate_fix_get
    if _newclass:fix = _swig_property(_ghmmwrapper.ghmm_dpstate_fix_get, _ghmmwrapper.ghmm_dpstate_fix_set)
    __swig_setmethods__["label"] = _ghmmwrapper.ghmm_dpstate_label_set
    __swig_getmethods__["label"] = _ghmmwrapper.ghmm_dpstate_label_get
    if _newclass:label = _swig_property(_ghmmwrapper.ghmm_dpstate_label_get, _ghmmwrapper.ghmm_dpstate_label_set)
    __swig_setmethods__["offset_x"] = _ghmmwrapper.ghmm_dpstate_offset_x_set
    __swig_getmethods__["offset_x"] = _ghmmwrapper.ghmm_dpstate_offset_x_get
    if _newclass:offset_x = _swig_property(_ghmmwrapper.ghmm_dpstate_offset_x_get, _ghmmwrapper.ghmm_dpstate_offset_x_set)
    __swig_setmethods__["offset_y"] = _ghmmwrapper.ghmm_dpstate_offset_y_set
    __swig_getmethods__["offset_y"] = _ghmmwrapper.ghmm_dpstate_offset_y_get
    if _newclass:offset_y = _swig_property(_ghmmwrapper.ghmm_dpstate_offset_y_get, _ghmmwrapper.ghmm_dpstate_offset_y_set)
    __swig_setmethods__["alphabet"] = _ghmmwrapper.ghmm_dpstate_alphabet_set
    __swig_getmethods__["alphabet"] = _ghmmwrapper.ghmm_dpstate_alphabet_get
    if _newclass:alphabet = _swig_property(_ghmmwrapper.ghmm_dpstate_alphabet_get, _ghmmwrapper.ghmm_dpstate_alphabet_set)
    __swig_setmethods__["xPosition"] = _ghmmwrapper.ghmm_dpstate_xPosition_set
    __swig_getmethods__["xPosition"] = _ghmmwrapper.ghmm_dpstate_xPosition_get
    if _newclass:xPosition = _swig_property(_ghmmwrapper.ghmm_dpstate_xPosition_get, _ghmmwrapper.ghmm_dpstate_xPosition_set)
    __swig_setmethods__["yPosition"] = _ghmmwrapper.ghmm_dpstate_yPosition_set
    __swig_getmethods__["yPosition"] = _ghmmwrapper.ghmm_dpstate_yPosition_get
    if _newclass:yPosition = _swig_property(_ghmmwrapper.ghmm_dpstate_yPosition_get, _ghmmwrapper.ghmm_dpstate_yPosition_set)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_dpstate()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dpstate
    __del__ = lambda self : None;
ghmm_dpstate_swigregister = _ghmmwrapper.ghmm_dpstate_swigregister
ghmm_dpstate_swigregister(ghmm_dpstate)


def dpstate_array_alloc(*args):
  return _ghmmwrapper.dpstate_array_alloc(*args)
dpstate_array_alloc = _ghmmwrapper.dpstate_array_alloc

def dpstate_array_getRef(*args):
  return _ghmmwrapper.dpstate_array_getRef(*args)
dpstate_array_getRef = _ghmmwrapper.dpstate_array_getRef

def dpstate_ptr_array_alloc(*args):
  return _ghmmwrapper.dpstate_ptr_array_alloc(*args)
dpstate_ptr_array_alloc = _ghmmwrapper.dpstate_ptr_array_alloc

def dpstate_ptr_array_getitem(*args):
  return _ghmmwrapper.dpstate_ptr_array_getitem(*args)
dpstate_ptr_array_getitem = _ghmmwrapper.dpstate_ptr_array_getitem

def dpstate_ptr_array_setitem(*args):
  return _ghmmwrapper.dpstate_ptr_array_setitem(*args)
dpstate_ptr_array_setitem = _ghmmwrapper.dpstate_ptr_array_setitem
class ghmm_dpmodel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_dpmodel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_dpmodel, name)
    __repr__ = _swig_repr
    __swig_setmethods__["N"] = _ghmmwrapper.ghmm_dpmodel_N_set
    __swig_getmethods__["N"] = _ghmmwrapper.ghmm_dpmodel_N_get
    if _newclass:N = _swig_property(_ghmmwrapper.ghmm_dpmodel_N_get, _ghmmwrapper.ghmm_dpmodel_N_set)
    __swig_setmethods__["M"] = _ghmmwrapper.ghmm_dpmodel_M_set
    __swig_getmethods__["M"] = _ghmmwrapper.ghmm_dpmodel_M_get
    if _newclass:M = _swig_property(_ghmmwrapper.ghmm_dpmodel_M_get, _ghmmwrapper.ghmm_dpmodel_M_set)
    __swig_setmethods__["s"] = _ghmmwrapper.ghmm_dpmodel_s_set
    __swig_getmethods__["s"] = _ghmmwrapper.ghmm_dpmodel_s_get
    if _newclass:s = _swig_property(_ghmmwrapper.ghmm_dpmodel_s_get, _ghmmwrapper.ghmm_dpmodel_s_set)
    __swig_setmethods__["prior"] = _ghmmwrapper.ghmm_dpmodel_prior_set
    __swig_getmethods__["prior"] = _ghmmwrapper.ghmm_dpmodel_prior_get
    if _newclass:prior = _swig_property(_ghmmwrapper.ghmm_dpmodel_prior_get, _ghmmwrapper.ghmm_dpmodel_prior_set)
    __swig_setmethods__["name"] = _ghmmwrapper.ghmm_dpmodel_name_set
    __swig_getmethods__["name"] = _ghmmwrapper.ghmm_dpmodel_name_get
    if _newclass:name = _swig_property(_ghmmwrapper.ghmm_dpmodel_name_get, _ghmmwrapper.ghmm_dpmodel_name_set)
    __swig_setmethods__["model_type"] = _ghmmwrapper.ghmm_dpmodel_model_type_set
    __swig_getmethods__["model_type"] = _ghmmwrapper.ghmm_dpmodel_model_type_get
    if _newclass:model_type = _swig_property(_ghmmwrapper.ghmm_dpmodel_model_type_get, _ghmmwrapper.ghmm_dpmodel_model_type_set)
    __swig_setmethods__["silent"] = _ghmmwrapper.ghmm_dpmodel_silent_set
    __swig_getmethods__["silent"] = _ghmmwrapper.ghmm_dpmodel_silent_get
    if _newclass:silent = _swig_property(_ghmmwrapper.ghmm_dpmodel_silent_get, _ghmmwrapper.ghmm_dpmodel_silent_set)
    __swig_setmethods__["maxorder"] = _ghmmwrapper.ghmm_dpmodel_maxorder_set
    __swig_getmethods__["maxorder"] = _ghmmwrapper.ghmm_dpmodel_maxorder_get
    if _newclass:maxorder = _swig_property(_ghmmwrapper.ghmm_dpmodel_maxorder_get, _ghmmwrapper.ghmm_dpmodel_maxorder_set)
    __swig_setmethods__["emission_history"] = _ghmmwrapper.ghmm_dpmodel_emission_history_set
    __swig_getmethods__["emission_history"] = _ghmmwrapper.ghmm_dpmodel_emission_history_get
    if _newclass:emission_history = _swig_property(_ghmmwrapper.ghmm_dpmodel_emission_history_get, _ghmmwrapper.ghmm_dpmodel_emission_history_set)
    __swig_setmethods__["tied_to"] = _ghmmwrapper.ghmm_dpmodel_tied_to_set
    __swig_getmethods__["tied_to"] = _ghmmwrapper.ghmm_dpmodel_tied_to_get
    if _newclass:tied_to = _swig_property(_ghmmwrapper.ghmm_dpmodel_tied_to_get, _ghmmwrapper.ghmm_dpmodel_tied_to_set)
    __swig_setmethods__["background_id"] = _ghmmwrapper.ghmm_dpmodel_background_id_set
    __swig_getmethods__["background_id"] = _ghmmwrapper.ghmm_dpmodel_background_id_get
    if _newclass:background_id = _swig_property(_ghmmwrapper.ghmm_dpmodel_background_id_get, _ghmmwrapper.ghmm_dpmodel_background_id_set)
    __swig_setmethods__["bp"] = _ghmmwrapper.ghmm_dpmodel_bp_set
    __swig_getmethods__["bp"] = _ghmmwrapper.ghmm_dpmodel_bp_get
    if _newclass:bp = _swig_property(_ghmmwrapper.ghmm_dpmodel_bp_get, _ghmmwrapper.ghmm_dpmodel_bp_set)
    __swig_setmethods__["topo_order"] = _ghmmwrapper.ghmm_dpmodel_topo_order_set
    __swig_getmethods__["topo_order"] = _ghmmwrapper.ghmm_dpmodel_topo_order_get
    if _newclass:topo_order = _swig_property(_ghmmwrapper.ghmm_dpmodel_topo_order_get, _ghmmwrapper.ghmm_dpmodel_topo_order_set)
    __swig_setmethods__["topo_order_length"] = _ghmmwrapper.ghmm_dpmodel_topo_order_length_set
    __swig_getmethods__["topo_order_length"] = _ghmmwrapper.ghmm_dpmodel_topo_order_length_get
    if _newclass:topo_order_length = _swig_property(_ghmmwrapper.ghmm_dpmodel_topo_order_length_get, _ghmmwrapper.ghmm_dpmodel_topo_order_length_set)
    __swig_setmethods__["number_of_alphabets"] = _ghmmwrapper.ghmm_dpmodel_number_of_alphabets_set
    __swig_getmethods__["number_of_alphabets"] = _ghmmwrapper.ghmm_dpmodel_number_of_alphabets_get
    if _newclass:number_of_alphabets = _swig_property(_ghmmwrapper.ghmm_dpmodel_number_of_alphabets_get, _ghmmwrapper.ghmm_dpmodel_number_of_alphabets_set)
    __swig_setmethods__["size_of_alphabet"] = _ghmmwrapper.ghmm_dpmodel_size_of_alphabet_set
    __swig_getmethods__["size_of_alphabet"] = _ghmmwrapper.ghmm_dpmodel_size_of_alphabet_get
    if _newclass:size_of_alphabet = _swig_property(_ghmmwrapper.ghmm_dpmodel_size_of_alphabet_get, _ghmmwrapper.ghmm_dpmodel_size_of_alphabet_set)
    __swig_setmethods__["number_of_d_seqs"] = _ghmmwrapper.ghmm_dpmodel_number_of_d_seqs_set
    __swig_getmethods__["number_of_d_seqs"] = _ghmmwrapper.ghmm_dpmodel_number_of_d_seqs_get
    if _newclass:number_of_d_seqs = _swig_property(_ghmmwrapper.ghmm_dpmodel_number_of_d_seqs_get, _ghmmwrapper.ghmm_dpmodel_number_of_d_seqs_set)
    __swig_setmethods__["max_offset_x"] = _ghmmwrapper.ghmm_dpmodel_max_offset_x_set
    __swig_getmethods__["max_offset_x"] = _ghmmwrapper.ghmm_dpmodel_max_offset_x_get
    if _newclass:max_offset_x = _swig_property(_ghmmwrapper.ghmm_dpmodel_max_offset_x_get, _ghmmwrapper.ghmm_dpmodel_max_offset_x_set)
    __swig_setmethods__["max_offset_y"] = _ghmmwrapper.ghmm_dpmodel_max_offset_y_set
    __swig_getmethods__["max_offset_y"] = _ghmmwrapper.ghmm_dpmodel_max_offset_y_get
    if _newclass:max_offset_y = _swig_property(_ghmmwrapper.ghmm_dpmodel_max_offset_y_get, _ghmmwrapper.ghmm_dpmodel_max_offset_y_set)
    __swig_setmethods__["debug"] = _ghmmwrapper.ghmm_dpmodel_debug_set
    __swig_getmethods__["debug"] = _ghmmwrapper.ghmm_dpmodel_debug_get
    if _newclass:debug = _swig_property(_ghmmwrapper.ghmm_dpmodel_debug_get, _ghmmwrapper.ghmm_dpmodel_debug_set)
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_dpmodel
    __del__ = lambda self : None;
    def viterbi_logp(self, *args): return _ghmmwrapper.ghmm_dpmodel_viterbi_logp(self, *args)
    def viterbi_propagate(self, *args): return _ghmmwrapper.ghmm_dpmodel_viterbi_propagate(self, *args)
    def viterbi_propagate_segment(self, *args): return _ghmmwrapper.ghmm_dpmodel_viterbi_propagate_segment(self, *args)
    def getState(self, *args): return _ghmmwrapper.ghmm_dpmodel_getState(self, *args)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_dpmodel()
        try: self.this.append(this)
        except: self.this = this
ghmm_dpmodel_swigregister = _ghmmwrapper.ghmm_dpmodel_swigregister
ghmm_dpmodel_swigregister(ghmm_dpmodel)


def ghmm_dpmodel_free(*args):
  return _ghmmwrapper.ghmm_dpmodel_free(*args)
ghmm_dpmodel_free = _ghmmwrapper.ghmm_dpmodel_free

def dpmodel_array_alloc(*args):
  return _ghmmwrapper.dpmodel_array_alloc(*args)
dpmodel_array_alloc = _ghmmwrapper.dpmodel_array_alloc

def dpmodel_array_getRef(*args):
  return _ghmmwrapper.dpmodel_array_getRef(*args)
dpmodel_array_getRef = _ghmmwrapper.dpmodel_array_getRef

def dpmodel_ptr_array_alloc(*args):
  return _ghmmwrapper.dpmodel_ptr_array_alloc(*args)
dpmodel_ptr_array_alloc = _ghmmwrapper.dpmodel_ptr_array_alloc

def dpmodel_ptr_array_getitem(*args):
  return _ghmmwrapper.dpmodel_ptr_array_getitem(*args)
dpmodel_ptr_array_getitem = _ghmmwrapper.dpmodel_ptr_array_getitem

def dpmodel_ptr_array_setitem(*args):
  return _ghmmwrapper.dpmodel_ptr_array_setitem(*args)
dpmodel_ptr_array_setitem = _ghmmwrapper.dpmodel_ptr_array_setitem

def ghmm_dpmodel_pair(*args):
  return _ghmmwrapper.ghmm_dpmodel_pair(*args)
ghmm_dpmodel_pair = _ghmmwrapper.ghmm_dpmodel_pair
class ghmm_xmlfile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_xmlfile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_xmlfile, name)
    __repr__ = _swig_repr
    __swig_setmethods__["noModels"] = _ghmmwrapper.ghmm_xmlfile_noModels_set
    __swig_getmethods__["noModels"] = _ghmmwrapper.ghmm_xmlfile_noModels_get
    if _newclass:noModels = _swig_property(_ghmmwrapper.ghmm_xmlfile_noModels_get, _ghmmwrapper.ghmm_xmlfile_noModels_set)
    __swig_setmethods__["modelType"] = _ghmmwrapper.ghmm_xmlfile_modelType_set
    __swig_getmethods__["modelType"] = _ghmmwrapper.ghmm_xmlfile_modelType_get
    if _newclass:modelType = _swig_property(_ghmmwrapper.ghmm_xmlfile_modelType_get, _ghmmwrapper.ghmm_xmlfile_modelType_set)
    __swig_getmethods__["model"] = _ghmmwrapper.ghmm_xmlfile_model_get
    if _newclass:model = _swig_property(_ghmmwrapper.ghmm_xmlfile_model_get)
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_xmlfile
    __del__ = lambda self : None;
    def get_cmodel(self, *args): return _ghmmwrapper.ghmm_xmlfile_get_cmodel(self, *args)
    def get_dmodel(self, *args): return _ghmmwrapper.ghmm_xmlfile_get_dmodel(self, *args)
    def get_dpmodel(self, *args): return _ghmmwrapper.ghmm_xmlfile_get_dpmodel(self, *args)
    def get_dsmodel(self, *args): return _ghmmwrapper.ghmm_xmlfile_get_dsmodel(self, *args)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_xmlfile()
        try: self.this.append(this)
        except: self.this = this
ghmm_xmlfile_swigregister = _ghmmwrapper.ghmm_xmlfile_swigregister
ghmm_xmlfile_swigregister(ghmm_xmlfile)

class ghmm_xmlfile_model(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ghmm_xmlfile_model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ghmm_xmlfile_model, name)
    __repr__ = _swig_repr
    __swig_setmethods__["c"] = _ghmmwrapper.ghmm_xmlfile_model_c_set
    __swig_getmethods__["c"] = _ghmmwrapper.ghmm_xmlfile_model_c_get
    if _newclass:c = _swig_property(_ghmmwrapper.ghmm_xmlfile_model_c_get, _ghmmwrapper.ghmm_xmlfile_model_c_set)
    __swig_setmethods__["d"] = _ghmmwrapper.ghmm_xmlfile_model_d_set
    __swig_getmethods__["d"] = _ghmmwrapper.ghmm_xmlfile_model_d_get
    if _newclass:d = _swig_property(_ghmmwrapper.ghmm_xmlfile_model_d_get, _ghmmwrapper.ghmm_xmlfile_model_d_set)
    __swig_setmethods__["dp"] = _ghmmwrapper.ghmm_xmlfile_model_dp_set
    __swig_getmethods__["dp"] = _ghmmwrapper.ghmm_xmlfile_model_dp_get
    if _newclass:dp = _swig_property(_ghmmwrapper.ghmm_xmlfile_model_dp_get, _ghmmwrapper.ghmm_xmlfile_model_dp_set)
    __swig_setmethods__["ds"] = _ghmmwrapper.ghmm_xmlfile_model_ds_set
    __swig_getmethods__["ds"] = _ghmmwrapper.ghmm_xmlfile_model_ds_get
    if _newclass:ds = _swig_property(_ghmmwrapper.ghmm_xmlfile_model_ds_get, _ghmmwrapper.ghmm_xmlfile_model_ds_set)
    def __init__(self): 
        this = _ghmmwrapper.new_ghmm_xmlfile_model()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ghmmwrapper.delete_ghmm_xmlfile_model
    __del__ = lambda self : None;
ghmm_xmlfile_model_swigregister = _ghmmwrapper.ghmm_xmlfile_model_swigregister
ghmm_xmlfile_model_swigregister(ghmm_xmlfile_model)


def ghmm_xmlfile_parse(*args):
  return _ghmmwrapper.ghmm_xmlfile_parse(*args)
ghmm_xmlfile_parse = _ghmmwrapper.ghmm_xmlfile_parse

def ghmm_xmlfile_validate(*args):
  return _ghmmwrapper.ghmm_xmlfile_validate(*args)
ghmm_xmlfile_validate = _ghmmwrapper.ghmm_xmlfile_validate

def ghmm_xmlfile_write(*args):
  return _ghmmwrapper.ghmm_xmlfile_write(*args)
ghmm_xmlfile_write = _ghmmwrapper.ghmm_xmlfile_write

def free(*args):
  return _ghmmwrapper.free(*args)
free = _ghmmwrapper.free

def int_array_alloc(*args):
  return _ghmmwrapper.int_array_alloc(*args)
int_array_alloc = _ghmmwrapper.int_array_alloc

def int_array_getitem(*args):
  return _ghmmwrapper.int_array_getitem(*args)
int_array_getitem = _ghmmwrapper.int_array_getitem

def int_array_setitem(*args):
  return _ghmmwrapper.int_array_setitem(*args)
int_array_setitem = _ghmmwrapper.int_array_setitem

def long_array_alloc(*args):
  return _ghmmwrapper.long_array_alloc(*args)
long_array_alloc = _ghmmwrapper.long_array_alloc

def long_array_getitem(*args):
  return _ghmmwrapper.long_array_getitem(*args)
long_array_getitem = _ghmmwrapper.long_array_getitem

def long_array_setitem(*args):
  return _ghmmwrapper.long_array_setitem(*args)
long_array_setitem = _ghmmwrapper.long_array_setitem

def double_array_alloc(*args):
  return _ghmmwrapper.double_array_alloc(*args)
double_array_alloc = _ghmmwrapper.double_array_alloc

def double_array_getitem(*args):
  return _ghmmwrapper.double_array_getitem(*args)
double_array_getitem = _ghmmwrapper.double_array_getitem

def double_array_setitem(*args):
  return _ghmmwrapper.double_array_setitem(*args)
double_array_setitem = _ghmmwrapper.double_array_setitem

def list2int_array(*args):
  return _ghmmwrapper.list2int_array(*args)
list2int_array = _ghmmwrapper.list2int_array

def int_array2list(*args):
  return _ghmmwrapper.int_array2list(*args)
int_array2list = _ghmmwrapper.int_array2list

def list2double_array(*args):
  return _ghmmwrapper.list2double_array(*args)
list2double_array = _ghmmwrapper.list2double_array

def double_array2list(*args):
  return _ghmmwrapper.double_array2list(*args)
double_array2list = _ghmmwrapper.double_array2list

def int_matrix_alloc(*args):
  return _ghmmwrapper.int_matrix_alloc(*args)
int_matrix_alloc = _ghmmwrapper.int_matrix_alloc

def int_matrix_alloc_row(*args):
  return _ghmmwrapper.int_matrix_alloc_row(*args)
int_matrix_alloc_row = _ghmmwrapper.int_matrix_alloc_row

def int_matrix_free(*args):
  return _ghmmwrapper.int_matrix_free(*args)
int_matrix_free = _ghmmwrapper.int_matrix_free

def int_matrix_get_col(*args):
  return _ghmmwrapper.int_matrix_get_col(*args)
int_matrix_get_col = _ghmmwrapper.int_matrix_get_col

def int_matrix_set_col(*args):
  return _ghmmwrapper.int_matrix_set_col(*args)
int_matrix_set_col = _ghmmwrapper.int_matrix_set_col

def int_matrix_getitem(*args):
  return _ghmmwrapper.int_matrix_getitem(*args)
int_matrix_getitem = _ghmmwrapper.int_matrix_getitem

def int_matrix_setitem(*args):
  return _ghmmwrapper.int_matrix_setitem(*args)
int_matrix_setitem = _ghmmwrapper.int_matrix_setitem

def double_matrix_alloc(*args):
  return _ghmmwrapper.double_matrix_alloc(*args)
double_matrix_alloc = _ghmmwrapper.double_matrix_alloc

def double_matrix_alloc_row(*args):
  return _ghmmwrapper.double_matrix_alloc_row(*args)
double_matrix_alloc_row = _ghmmwrapper.double_matrix_alloc_row

def double_matrix_free(*args):
  return _ghmmwrapper.double_matrix_free(*args)
double_matrix_free = _ghmmwrapper.double_matrix_free

def double_matrix_get_col(*args):
  return _ghmmwrapper.double_matrix_get_col(*args)
double_matrix_get_col = _ghmmwrapper.double_matrix_get_col

def double_matrix_set_col(*args):
  return _ghmmwrapper.double_matrix_set_col(*args)
double_matrix_set_col = _ghmmwrapper.double_matrix_set_col

def double_matrix_getitem(*args):
  return _ghmmwrapper.double_matrix_getitem(*args)
double_matrix_getitem = _ghmmwrapper.double_matrix_getitem

def double_matrix_setitem(*args):
  return _ghmmwrapper.double_matrix_setitem(*args)
double_matrix_setitem = _ghmmwrapper.double_matrix_setitem
# This file is compatible with both classic and new-style classes.


